#!/bin/sh
#BHEADER***********************************************************************
# (c) 1998   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision$
#EHEADER***********************************************************************

INTERNAL_HEADER=krylov.h

#===========================================================================
# Include guards and other includes
#===========================================================================

cat > $INTERNAL_HEADER < all_krylov.h
cat >> $INTERNAL_HEADER < bicgstab.h
cat >> $INTERNAL_HEADER < cgnr.h
cat >> $INTERNAL_HEADER < gmres.h
cat >> $INTERNAL_HEADER < pcg.h

cat >> $INTERNAL_HEADER <<@

#ifndef hypre_KRYLOV_HEADER
#define hypre_KRYLOV_HEADER

#ifdef __cplusplus
extern "C" {
#endif

@

#===========================================================================
# Structures and prototypes
#===========================================================================

../utilities/protos [!F]*.c               >> $INTERNAL_HEADER

#===========================================================================
# Include guards
#===========================================================================

cat >> $INTERNAL_HEADER <<@

#ifdef __cplusplus
}
#endif

#endif

@

