#!/bin/sh
#BHEADER**********************************************************************
# Copyright (c) 2007, Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory.
# Written by the HYPRE team. UCRL-CODE-222953.
# All rights reserved.
#
# This file is part of HYPRE (see http://www.llnl.gov/CASC/hypre/).
# Please see the COPYRIGHT_and_LICENSE file for the copyright notice, 
# disclaimer, contact information and the GNU Lesser General Public License.
#
# HYPRE is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License (as published by the Free Software 
# Foundation) version 2.1 dated February 1999.
#
# HYPRE is distributed in the hope that it will be useful, but WITHOUT ANY 
# WARRANTY; without even the IMPLIED WARRANTY OF MERCHANTABILITY or FITNESS 
# FOR A PARTICULAR PURPOSE.  See the terms and conditions of the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
# $Revision$
#EHEADER**********************************************************************





#=============================================================================
# This Script attempts to determine the architecture to use.
#=============================================================================

AMG_OS=""
AMG_ARCH=""

#=============================================================================
# Determine the OS
#=============================================================================

then
fi

#=============================================================================
# Based on what we found from system queries set AMG_ARCH
#=============================================================================

if [ -z "$AMG_ARCH" ]
then
   case "$AMG_OS" in
      SunOS)
         case "$AMG_OS_Release" in	
            4.1.3) AMG_ARCH="sunos";;
            5.4)   AMG_ARCH="solaris";;
            5.5)   AMG_ARCH="solaris";;
            5.6)   AMG_ARCH="solaris";;
         esac;;
      IRIX64)
         AMG_ARCH="irix";;
      OSF1)
         AMG_ARCH="dec";;
      CYGWIN32/95)
         AMG_ARCH="cygwin32";;
      CYGWIN32/NT)
         AMG_ARCH="cygwin32";;
   esac
fi

