#!/bin/sh
#BHEADER**********************************************************************
# Copyright (c) 2008,  Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory.
# This file is part of HYPRE.  See file COPYRIGHT for details.
#
# HYPRE is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License (as published by the Free
# Software Foundation) version 2.1 dated February 1999.
#
# $Revision$
#EHEADER**********************************************************************








#=============================================================================
# This Script attempts to determine the architecture to use.
#=============================================================================

AMG_OS=""
AMG_ARCH=""

#=============================================================================
# Determine the OS
#=============================================================================

then
fi

#=============================================================================
# Based on what we found from system queries set AMG_ARCH
#=============================================================================

if [ -z "$AMG_ARCH" ]
then
   case "$AMG_OS" in
      SunOS)
         case "$AMG_OS_Release" in	
            4.1.3) AMG_ARCH="sunos";;
            5.4)   AMG_ARCH="solaris";;
            5.5)   AMG_ARCH="solaris";;
            5.6)   AMG_ARCH="solaris";;
         esac;;
      IRIX64)
         AMG_ARCH="irix";;
      OSF1)
         AMG_ARCH="dec";;
      CYGWIN32/95)
         AMG_ARCH="cygwin32";;
      CYGWIN32/NT)
         AMG_ARCH="cygwin32";;
   esac
fi

