/*
 * File:          ClassInfo_Module.c
 * Symbol:        SIDL.ClassInfo-v0.8.1
 * Symbol Type:   interface
 * Babel Version: 0.8.0
 * Release:       $Name: V1-9-0b $
 * Revision:      @(#) $Id: ClassInfo_Module.c,v 1.1 2003/02/12 23:26:50 painter Exp $
 * Description:   implement a C extension type for a SIDL extendable
 * 
 * Copyright (c) 2000-2002, The Regents of the University of California.
 * Produced at the Lawrence Livermore National Laboratory.
 * Written by the Components Team <components@llnl.gov>
 * All rights reserved.
 * 
 * This file is part of Babel. For more information, see
 * http://www.llnl.gov/CASC/components/. Please read the COPYRIGHT file
 * for Our Notice and the LICENSE file for the GNU Lesser General Public
 * License.
 * 
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License (as published by
 * the Free Software Foundation) version 2.1 dated February 1999.
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the IMPLIED WARRANTY OF
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the terms and
 * conditions of the GNU Lesser General Public License for more details.
 * 
 * You should have recieved a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 * 
 * WARNING: Automatically generated; changes will be lost
 * 
 * babel-version = 0.8.0
 */

/*
 * THIS CODE IS AUTOMATICALLY GENERATED BY THE BABEL
 * COMPILER. DO NOT EDIT THIS!
 * 
 * This file contains the implementation of a Python C
 * extension type (i.e. a Python type implemented in C).
 * This extension type provides Python interface to the
 * SIDL type SIDL.ClassInfo.
 */


/**
 * Symbol "SIDL.ClassInfo" (version 0.8.1)
 * 
 * This provides an interface to the meta-data available on the
 * class.
 */
#define SIDL_ClassInfo_INTERNAL 1
#include "SIDL_ClassInfo_Module.h"
#ifndef included_SIDL_ClassInfo_IOR_h
#include "SIDL_ClassInfo_IOR.h"
#endif
#include "SIDLObjA.h"
#include "SIDLPyArrays.h"
#include "Numeric/arrayobject.h"
#ifndef included_SIDL_Loader_h
#include "SIDL_Loader.h"
#endif
#ifndef included_SIDL_header_h
#include "SIDL_header.h"
#endif
#ifndef included_SIDL_interface_IOR_h
#include "SIDL_interface_IOR.h"
#endif
#include "SIDL_BaseInterface_Module.h"
#include <stdlib.h>
#include <string.h>

static PyObject *
pStub_ClassInfo_addRef(PyObject *_self, PyObject *_args, PyObject *_kwdict) {
  PyObject *_return_value = NULL;
  struct SIDL_ClassInfo__object *_self_ior =
    ((struct SIDL_ClassInfo__object *)
     SIDL_Cast(_self, "SIDL.ClassInfo"));
  if (_self_ior) {
    static char *_kwlist[] = {
      NULL
    };
    const int _okay = PyArg_ParseTupleAndKeywords(
      _args, _kwdict, 
      "", _kwlist);
    if (_okay) {
      (*(_self_ior->d_epv->f_addRef))(_self_ior->d_object);
      _return_value = Py_None;
      Py_INCREF(_return_value);
    }
  }
  else {
    PyErr_SetString(PyExc_TypeError, 
      "self pointer is not a SIDL.ClassInfo");
  }
  return _return_value;
}

static PyObject *
pStub_ClassInfo_deleteRef(PyObject *_self, PyObject *_args,                   \
  PyObject *_kwdict) {
  PyObject *_return_value = NULL;
  struct SIDL_ClassInfo__object *_self_ior =
    ((struct SIDL_ClassInfo__object *)
     SIDL_Cast(_self, "SIDL.ClassInfo"));
  if (_self_ior) {
    static char *_kwlist[] = {
      NULL
    };
    const int _okay = PyArg_ParseTupleAndKeywords(
      _args, _kwdict, 
      "", _kwlist);
    if (_okay) {
      (*(_self_ior->d_epv->f_deleteRef))(_self_ior->d_object);
      _return_value = Py_None;
      Py_INCREF(_return_value);
    }
  }
  else {
    PyErr_SetString(PyExc_TypeError, 
      "self pointer is not a SIDL.ClassInfo");
  }
  return _return_value;
}

static PyObject *
pStub_ClassInfo_isSame(PyObject *_self, PyObject *_args, PyObject *_kwdict) {
  PyObject *_return_value = NULL;
  struct SIDL_ClassInfo__object *_self_ior =
    ((struct SIDL_ClassInfo__object *)
     SIDL_Cast(_self, "SIDL.ClassInfo"));
  if (_self_ior) {
    struct SIDL_BaseInterface__object* iobj = NULL;
    static char *_kwlist[] = {
      "iobj",
      NULL
    };
    const int _okay = PyArg_ParseTupleAndKeywords(
      _args, _kwdict, 
      "O&", _kwlist,
      (void *)SIDL_BaseInterface__convert, &iobj);
    if (_okay) {
      SIDL_bool _return = (SIDL_bool) 0;
      int _proxy__return;
      _return = (*(_self_ior->d_epv->f_isSame))(_self_ior->d_object, iobj);
      _proxy__return = _return;
      _return_value = Py_BuildValue(
        "i",
        _proxy__return);
      SIDL_BaseInterface_deref(iobj);
    }
  }
  else {
    PyErr_SetString(PyExc_TypeError, 
      "self pointer is not a SIDL.ClassInfo");
  }
  return _return_value;
}

static PyObject *
pStub_ClassInfo_queryInt(PyObject *_self, PyObject *_args,                    \
  PyObject *_kwdict) {
  PyObject *_return_value = NULL;
  struct SIDL_ClassInfo__object *_self_ior =
    ((struct SIDL_ClassInfo__object *)
     SIDL_Cast(_self, "SIDL.ClassInfo"));
  if (_self_ior) {
    char* name = NULL;
    static char *_kwlist[] = {
      "name",
      NULL
    };
    const int _okay = PyArg_ParseTupleAndKeywords(
      _args, _kwdict, 
      "z", _kwlist,
      &name);
    if (_okay) {
      struct SIDL_BaseInterface__object* _return = NULL;
      _return = (*(_self_ior->d_epv->f_queryInt))(_self_ior->d_object, name);
      _return_value = Py_BuildValue(
        "O&",
        (void *)SIDL_BaseInterface__wrap, _return);
    }
  }
  else {
    PyErr_SetString(PyExc_TypeError, 
      "self pointer is not a SIDL.ClassInfo");
  }
  return _return_value;
}

static PyObject *
pStub_ClassInfo_isType(PyObject *_self, PyObject *_args, PyObject *_kwdict) {
  PyObject *_return_value = NULL;
  struct SIDL_ClassInfo__object *_self_ior =
    ((struct SIDL_ClassInfo__object *)
     SIDL_Cast(_self, "SIDL.ClassInfo"));
  if (_self_ior) {
    char* name = NULL;
    static char *_kwlist[] = {
      "name",
      NULL
    };
    const int _okay = PyArg_ParseTupleAndKeywords(
      _args, _kwdict, 
      "z", _kwlist,
      &name);
    if (_okay) {
      SIDL_bool _return = (SIDL_bool) 0;
      int _proxy__return;
      _return = (*(_self_ior->d_epv->f_isType))(_self_ior->d_object, name);
      _proxy__return = _return;
      _return_value = Py_BuildValue(
        "i",
        _proxy__return);
    }
  }
  else {
    PyErr_SetString(PyExc_TypeError, 
      "self pointer is not a SIDL.ClassInfo");
  }
  return _return_value;
}

static PyObject *
pStub_ClassInfo_getName(PyObject *_self, PyObject *_args, PyObject *_kwdict) {
  PyObject *_return_value = NULL;
  struct SIDL_ClassInfo__object *_self_ior =
    ((struct SIDL_ClassInfo__object *)
     SIDL_Cast(_self, "SIDL.ClassInfo"));
  if (_self_ior) {
    static char *_kwlist[] = {
      NULL
    };
    const int _okay = PyArg_ParseTupleAndKeywords(
      _args, _kwdict, 
      "", _kwlist);
    if (_okay) {
      char* _return = NULL;
      _return = (*(_self_ior->d_epv->f_getName))(_self_ior->d_object);
      _return_value = Py_BuildValue(
        "z",
        _return);
      free((void *)_return);
    }
  }
  else {
    PyErr_SetString(PyExc_TypeError, 
      "self pointer is not a SIDL.ClassInfo");
  }
  return _return_value;
}

static PyObject *
pStub_ClassInfo_getIORVersion(PyObject *_self, PyObject *_args,               \
  PyObject *_kwdict) {
  PyObject *_return_value = NULL;
  struct SIDL_ClassInfo__object *_self_ior =
    ((struct SIDL_ClassInfo__object *)
     SIDL_Cast(_self, "SIDL.ClassInfo"));
  if (_self_ior) {
    static char *_kwlist[] = {
      NULL
    };
    const int _okay = PyArg_ParseTupleAndKeywords(
      _args, _kwdict, 
      "", _kwlist);
    if (_okay) {
      char* _return = NULL;
      _return = (*(_self_ior->d_epv->f_getIORVersion))(_self_ior->d_object);
      _return_value = Py_BuildValue(
        "z",
        _return);
      free((void *)_return);
    }
  }
  else {
    PyErr_SetString(PyExc_TypeError, 
      "self pointer is not a SIDL.ClassInfo");
  }
  return _return_value;
}

static PyObject *
_createCast(PyObject *self, PyObject *args) {
  struct SIDL_ClassInfo__object *optarg = NULL;
  int _okay = PyArg_ParseTuple(args, "O&", (void *)SIDL_ClassInfo__convert,   \
    &optarg);
  if (_okay) {
    if (optarg) {
      (*(optarg->d_epv->f_addRef))(optarg->d_object);
    }
    return SIDL_ClassInfo__wrap(optarg);
  }
  return NULL;
}

static PyMethodDef _ClassInfoModuleMethods[] = {
  { "ClassInfo", _createCast, METH_VARARGS, "Constructor and/or cast method for SIDL.ClassInfo"
   },
  { NULL, NULL }
};

static PyMethodDef _ClassInfoObjectMethods[] = {
  { "addRef", (PyCFunction)pStub_ClassInfo_addRef,
  (METH_VARARGS | METH_KEYWORDS),
"\
addRef()\n\
RETURNS\n\
    None\n\
\n\
\
<p>\n\
Add one to the intrinsic reference count in the underlying object.\n\
Object in <code>SIDL</code> have an intrinsic reference count.\n\
Objects continue to exist as long as the reference count is\n\
positive. Clients should call this method whenever they\n\
create another ongoing reference to an object or interface.\n\
</p>\n\
<p>\n\
This does not have a return value because there is no language\n\
independent type that can refer to an interface or a\n\
class.\n\
</p>"
   },
  { "deleteRef", (PyCFunction)pStub_ClassInfo_deleteRef,
  (METH_VARARGS | METH_KEYWORDS),
"\
deleteRef()\n\
RETURNS\n\
    None\n\
\n\
\
Decrease by one the intrinsic reference count in the underlying\n\
object, and delete the object if the reference is non-positive.\n\
Objects in <code>SIDL</code> have an intrinsic reference count.\n\
Clients should call this method whenever they remove a\n\
reference to an object or interface."
   },
  { "getIORVersion", (PyCFunction)pStub_ClassInfo_getIORVersion,
  (METH_VARARGS | METH_KEYWORDS),
"\
getIORVersion()\n\
RETURNS\n\
   (string _return)\n\
\n\
\
Get the version of the intermediate object representation.\n\
This will be in the form of major_version.minor_version."
   },
  { "getName", (PyCFunction)pStub_ClassInfo_getName,
  (METH_VARARGS | METH_KEYWORDS),
"\
getName()\n\
RETURNS\n\
   (string _return)\n\
\n\
\
Return the name of the class."
   },
  { "isSame", (PyCFunction)pStub_ClassInfo_isSame,
  (METH_VARARGS | METH_KEYWORDS),
"\
isSame(in SIDL.BaseInterface iobj)\n\
RETURNS\n\
   (bool _return)\n\
\n\
\
Return true if and only if <code>obj</code> refers to the same\n\
object as this object."
   },
  { "isType", (PyCFunction)pStub_ClassInfo_isType,
  (METH_VARARGS | METH_KEYWORDS),
"\
isType(in string name)\n\
RETURNS\n\
   (bool _return)\n\
\n\
\
Return whether this object is an instance of the specified type.\n\
The string name must be the <code>SIDL</code> type name.  This\n\
routine will return <code>true</code> if and only if a cast to\n\
the string type name would succeed."
   },
  { "queryInt", (PyCFunction)pStub_ClassInfo_queryInt,
  (METH_VARARGS | METH_KEYWORDS),
"\
queryInt(in string name)\n\
RETURNS\n\
   (SIDL.BaseInterface _return)\n\
\n\
\
Check whether the object can support the specified interface or\n\
class.  If the <code>SIDL</code> type name in <code>name</code>\n\
is supported, then a reference to that object is returned with the\n\
reference count incremented.  The callee will be responsible for\n\
calling <code>deleteRef</code> on the returned object.  If\n\
the specified type is not supported, then a null reference is\n\
returned."
   },
  { NULL, NULL }
};

SIDL_ClassInfo__wrap_RETURN
SIDL_ClassInfo__wrap SIDL_ClassInfo__wrap_PROTO {
  return SIDL_Interface_Create((struct SIDL_BaseInterface__object *) sidlobj, \
    _ClassInfoObjectMethods, SIDL_PyStealRef);
}

SIDL_ClassInfo__weakRef_RETURN
SIDL_ClassInfo__weakRef SIDL_ClassInfo__weakRef_PROTO {
  return SIDL_Interface_Create((struct SIDL_BaseInterface__object *) sidlobj, \
    _ClassInfoObjectMethods, SIDL_PyWeakRef);
}

SIDL_ClassInfo_deref_RETURN
SIDL_ClassInfo_deref SIDL_ClassInfo_deref_PROTO {
  if (sidlobj) {
    (*(sidlobj->d_epv->f_deleteRef))(sidlobj->d_object);
  }
}

SIDL_ClassInfo__newRef_RETURN
SIDL_ClassInfo__newRef SIDL_ClassInfo__newRef_PROTO {
  return SIDL_Interface_Create((struct SIDL_BaseInterface__object *) sidlobj, \
    _ClassInfoObjectMethods, SIDL_PyNewRef);
}

SIDL_ClassInfo__addRef_RETURN
SIDL_ClassInfo__addRef SIDL_ClassInfo__addRef_PROTO {
  if (sidlobj) {
    (*(sidlobj->d_epv->f_addRef))(sidlobj->d_object);
  }
}

SIDL_ClassInfo__convert_RETURN
SIDL_ClassInfo__convert SIDL_ClassInfo__convert_PROTO {
  *sidlobj = SIDL_Cast(obj, "SIDL.ClassInfo");
  if (*sidlobj) {
    (*((*sidlobj)->d_epv->f_addRef))((*sidlobj)->d_object);
  }
  else if (obj != Py_None) {
    PyErr_SetString(PyExc_TypeError, 
      "argument is not a(n) SIDL.ClassInfo");
    return 0;
  }
  return 1;
}

static int
_convertPython(void *sidlarray, const int *ind, PyObject *pyobj)
{
  struct SIDL_ClassInfo__object *sidlobj;
  if (SIDL_ClassInfo__convert(pyobj, &sidlobj)) {
    SIDL_interface__array_set((struct SIDL_interface__array *)sidlarray,
    ind, (struct SIDL_BaseInterface__object *)sidlobj);
    return FALSE;
  }
  return TRUE;
}

SIDL_ClassInfo__convert_python_array_RETURN
SIDL_ClassInfo__convert_python_array                                          \
  SIDL_ClassInfo__convert_python_array_PROTO {
  int result = 0;
  PyObject *pya = PyArray_FromObject(obj, PyArray_OBJECT, 0, 0);
  *sidlarray = NULL;
  if (pya) {
    if (PyArray_OBJECT == ((PyArrayObject *)pya)->descr->type_num) {
      int dimen, *lower, *upper, *stride;
      if (SIDL_array__extract_python_info
        (pya, &dimen, &lower, &upper, &stride))
      {
          *sidlarray = (struct                                                \
            SIDL_ClassInfo__array*)SIDL_interface__array_createRow
          (dimen, lower, upper);
        free(stride);
        free(upper);
        free(lower);
        result = SIDL_array__convert_python
          (pya, dimen, *sidlarray, _convertPython);
        if (*sidlarray && !result) {
          SIDL_interface__array_deleteRef(
            (struct  SIDL_interface__array *)*sidlarray);
          *sidlarray = NULL;
        }
      }
    }
    Py_DECREF(pya);
  }
  return result;
}

static int
_convertSIDL(void *sidlarray, const int *ind, PyObject **dest)
{
  struct SIDL_ClassInfo__object *sidlobj = (struct SIDL_ClassInfo__object*)
  SIDL_interface__array_get((struct SIDL_interface__array *)
    sidlarray, ind);
  *dest = SIDL_ClassInfo__wrap(sidlobj);
  return (*dest == NULL);
}

SIDL_ClassInfo__convert_sidl_array_RETURN
  SIDL_ClassInfo__convert_sidl_array SIDL_ClassInfo__convert_sidl_array_PROTO \
    {PyObject *pya = NULL;
  if (sidlarray) {
    const int dimen = SIDL_interface__array_dimen(
      (struct SIDL_interface__array *)sidlarray);
    int i;
    int *lower = (int *)malloc(sizeof(int) * dimen);
    int *upper = (int *)malloc(sizeof(int) * dimen);
    int *numelem = (int *)malloc(sizeof(int) * dimen);
    for(i = 0; i < dimen; ++i) {
      lower[i] = SIDL_interface__array_lower(
        (struct SIDL_interface__array *)sidlarray, i);
      upper[i] = SIDL_interface__array_upper(
        (struct SIDL_interface__array *)sidlarray, i);
      numelem[i] = 1 + upper[i] - lower[i];
    }
    pya = PyArray_FromDims(dimen, numelem, PyArray_OBJECT);
    if (pya) {
      if (!SIDL_array__convert_sidl(pya, dimen, lower, upper,
        numelem, sidlarray, _convertSIDL))
      {
        Py_DECREF(pya);
        pya = NULL;
      }
    }
    free(numelem);
    free(upper);
    free(lower);
  }
  return pya;
}

SIDL_ClassInfo__destroy_sidl_array_RETURN
SIDL_ClassInfo__destroy_sidl_array SIDL_ClassInfo__destroy_sidl_array_PROTO {
  if (sidlarray) {
    SIDL_interface__array_deleteRef(
      (struct SIDL_interface__array *)sidlarray);
  }
}
void
initClassInfo(void) {
  PyObject *module, *dict, *c_api;
  static void *ExternalAPI[SIDL_ClassInfo__API_NUM];
  module = Py_InitModule3("ClassInfo", _ClassInfoModuleMethods, "\
\
This provides an interface to the meta-data available on the\n\
class."
  );
  dict = PyModule_GetDict(module);
  ExternalAPI[SIDL_ClassInfo__wrap_NUM] = (void*)SIDL_ClassInfo__wrap;
  ExternalAPI[SIDL_ClassInfo__convert_NUM] = (void*)SIDL_ClassInfo__convert;
  ExternalAPI[SIDL_ClassInfo__convert_python_array_NUM] =                     \
    (void*)SIDL_ClassInfo__convert_python_array;
  ExternalAPI[SIDL_ClassInfo__convert_sidl_array_NUM] =                       \
    (void*)SIDL_ClassInfo__convert_sidl_array;
  ExternalAPI[SIDL_ClassInfo__destroy_sidl_array_NUM] =                       \
    (void*)SIDL_ClassInfo__destroy_sidl_array;
  ExternalAPI[SIDL_ClassInfo__weakRef_NUM] = (void*)SIDL_ClassInfo__weakRef;
  ExternalAPI[SIDL_ClassInfo_deref_NUM] = (void*)SIDL_ClassInfo_deref;
  ExternalAPI[SIDL_ClassInfo__newRef_NUM] = (void*)SIDL_ClassInfo__newRef;
  ExternalAPI[SIDL_ClassInfo__addRef_NUM] = (void*)SIDL_ClassInfo__addRef;
  import_SIDLObjA();
  if (PyErr_Occurred()) {
    Py_FatalError("Error importing SIDLObjA module.");
  }
  c_api = PyCObject_FromVoidPtr((void *)ExternalAPI, NULL);
  PyDict_SetItemString(dict, "_C_API", c_api);
  Py_XDECREF(c_api);
  if (PyErr_Occurred()) {
    Py_FatalError("Cannot initialize Python module SIDL.ClassInfo.");
  }
  import_SIDLPyArrays();
  if (PyErr_Occurred()) {
    Py_FatalError("Error importing SIDLPyArrays module.");
  }
  import_array();
  if (PyErr_Occurred()) {
    Py_FatalError("Error importing Numeric Python module.");
  }
  SIDL_BaseInterface__import();
}
