#!/bin/bash
# Copyright (c) 1998 Lawrence Livermore National Security, LLC and other
# HYPRE Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

touch mup_fake_ext.h
cat *.h > mup_fake_int.h

../config/gen_code.sh mup_fake_ext.h mup_fake_int.h onlydef

rm -f mup_fake_ext.h
rm -f mup_fake_int.h

# rename def file and header guard
sed 's/MUP_FAKE_INT/MULTIVECTOR/' mup_fake_int_mup_def.h > _hypre_multivector_mup_def.h
rm -f mup_fake_int_mup_def.h
