#!/usr/bin/perl -i.BAK
# This perl script is very stupid.  It takes the files you specify on the
#  command line and coverts #include "foo.h" to the matching substitution.
#  It will die if you give it a directory name or a nonexistent file.
#  Your original file foo.cc will be moved to foo.c.BAK, overwriting any
#  existing foo.cc.BAK
#  Questions/bugs  should be forwarded to baallan@ca.sandia.gov
#
if( ! defined($ARGV[0]) ) {
    print STDERR "Usage: $0 files";
    exit 2;
}

while (<>) {
	s/\#include \"AztecDMSR_Matrix.h\"/#include \"mv\/AztecDMSR_Matrix.h\"/;
	s/\#include \"AztecDVBR_Matrix.h\"/#include \"mv\/AztecDVBR_Matrix.h\"/;
	s/\#include \"Aztec_Map.h\"/#include \"mv\/Aztec_Map.h\"/;
	s/\#include \"Aztec_Vector.h\"/#include \"mv\/Aztec_Vector.h\"/;
	s/\#include \"BDCRS_Matrix.h\"/#include \"mv\/BDCRS_Matrix.h\"/;
	s/\#include \"Blas.h\"/#include \"mv\/Blas.h\"/;
	s/\#include \"BlasLapack.h\"/#include \"mv\/BlasLapack.h\"/;
	s/\#include \"CCS_Matrix.h\"/#include \"mv\/CCS_Matrix.h\"/;
	s/\#include \"CRS2_Matrix.h\"/#include \"mv\/CRS2_Matrix.h\"/;
	s/\#include \"CRS_Matrix.h\"/#include \"mv\/CRS_Matrix.h\"/;
	s/\#include \"CommInfo.h\"/#include \"mv\/CommInfo.h\"/;
	s/\#include \"DCRS_Matrix.h\"/#include \"mv\/DCRS_Matrix.h\"/;
	s/\#include \"DenseMatrix.h\"/#include \"mv\/DenseMatrix.h\"/;
	s/\#include \"DenseVector.h\"/#include \"mv\/DenseVector.h\"/;
	s/\#include \"Dist_IntVector.h\"/#include \"mv\/Dist_IntVector.h\"/;
	s/\#include \"Dist_Vector.blas.h\"/#include \"mv\/Dist_Vector.blas.h\"/;
	s/\#include \"Dist_Vector.h\"/#include \"mv\/Dist_Vector.h\"/;
	s/\#include \"Dist_Vector.sa.h\"/#include \"mv\/Dist_Vector.sa.h\"/;
	s/\#include \"GlobalIDArray.h\"/#include \"mv\/GlobalIDArray.h\"/;
	s/\#include \"IntArray.h\"/#include \"mv\/IntArray.h\"/;
	s/\#include \"IntVector.h\"/#include \"mv\/IntVector.h\"/;
	s/\#include \"LinearEquations.h\"/#include \"mv\/LinearEquations.h\"/;
	s/\#include \"LocalCommData.h\"/#include \"mv\/LocalCommData.h\"/;
	s/\#include \"MVComm.h\"/#include \"mv\/MVComm.h\"/;
	s/\#include \"MVCommunicator.h\"/#include \"mv\/MVCommunicator.h\"/;
	s/\#include \"Map.h\"/#include \"mv\/Map.h\"/;
	s/\#include \"Matrix.h\"/#include \"mv\/Matrix.h\"/;
	s/\#include \"RowMatrix.h\"/#include \"mv\/RowMatrix.h\"/;
	s/\#include \"RsCRS_Matrix.h\"/#include \"mv\/RsCRS_Matrix.h\"/;
	s/\#include \"RsDCRS_Matrix.h\"/#include \"mv\/RsDCRS_Matrix.h\"/;
	s/\#include \"RsRDCRS_Matrix.h\"/#include \"mv\/RsRDCRS_Matrix.h\"/;
	s/\#include \"RsSCRS_Matrix.h\"/#include \"mv\/RsSCRS_Matrix.h\"/;
	s/\#include \"SCRS_Matrix.h\"/#include \"mv\/SCRS_Matrix.h\"/;
	s/\#include \"Seq_IntVector.h\"/#include \"mv\/Seq_IntVector.h\"/;
	s/\#include \"Seq_Vector.h\"/#include \"mv\/Seq_Vector.h\"/;
	s/\#include \"Vector.h\"/#include \"mv\/Vector.h\"/;
	s/\#include \"Solver.h\"/#include \"solver\/Solver.h\"/;
	s/\#include \"Preconditioner.h\"/#include \"pc\/Preconditioner.h\"/;
	s/\#include \"PKStandard.h\"/#include \"other\/PKStandard.h\"/;
	s/\#include \"SmartArray.cc\"/#include \"other\/SmartArray.cc\"/;
	s/\#include \"SmartArray.h\"/#include \"other\/SmartArray.h\"/;
	s/\#include \"basicDefs.h\"/#include \"other\/basicDefs.h\"/;
	s/\#include \"basicTypes.h\"/#include \"fei\/basicTypes.h\"/;
	s/\#include \"BiCGStab_Solver.h\"/#include \"solver\/BiCGStab_Solver.h\"/;
	s/\#include \"CGNE_Solver.h\"/#include \"solver\/CGNE_Solver.h\"/;
	s/\#include \"CGNR_Solver.h\"/#include \"solver\/CGNR_Solver.h\"/;
	s/\#include \"CGS_Solver.h\"/#include \"solver\/CGS_Solver.h\"/;
	s/\#include \"CG_Solver.h\"/#include \"solver\/CG_Solver.h\"/;
	s/\#include \"DefGMRES_Solver.h\"/#include \"solver\/DefGMRES_Solver.h\"/;
	s/\#include \"FGMRES_Solver.h\"/#include \"solver\/FGMRES_Solver.h\"/;
	s/\#include \"GMRES_Solver.h\"/#include \"solver\/GMRES_Solver.h\"/;
	s/\#include \"IterativeSolver.h\"/#include \"solver\/IterativeSolver.h\"/;
	s/\#include \"QMR2_Solver.h\"/#include \"solver\/QMR2_Solver.h\"/;
	s/\#include \"QMR_Solver.h\"/#include \"solver\/QMR_Solver.h\"/;
	s/\#include \"BlockJacobi_PC.h\"/#include \"pc\/BlockJacobi_PC.h\"/;
	s/\#include \"CGNE_BlockJacobi_PC.h\"/#include \"pc\/CGNE_BlockJacobi_PC.h\"/;
	s/\#include \"CGNE_Diagonal_PC.h\"/#include \"pc\/CGNE_Diagonal_PC.h\"/;
	s/\#include \"CGNE_Poly_PC.h\"/#include \"pc\/CGNE_Poly_PC.h\"/;
	s/\#include \"CGNR_Poly_PC.h\"/#include \"pc\/CGNR_Poly_PC.h\"/;
	s/\#include \"Composed_PC.h\"/#include \"pc\/Composed_PC.h\"/;
	s/\#include \"Diagonal_PC.h\"/#include \"pc\/Diagonal_PC.h\"/;
	s/\#include \"Identity_PC.h\"/#include \"pc\/Identity_PC.h\"/;
	s/\#include \"Poly_PC.h\"/#include \"pc\/Poly_PC.h\"/;
	s/\#include \"SPAI_PC.h\"/#include \"pc\/SPAI_PC.h\"/;
	s/\#include \"SPAI_qr.h\"/#include \"pc\/SPAI_qr.h\"/;
	s/\#include \"SPAI_hash_tables.h\"/#include \"pc\/SPAI_hash_tables.h\"/;
	s/\#include \"RowPreconditioner.h\"/#include \"pc\/RowPreconditioner.h\"/;
    print;
}
