#!/bin/sh
# Runs Babel to generate interfaces for standard languages.

# Output directories must be different so the make file babel.make
# won't get overwritten.  The server (-sC) directory name was chosen
# for backwards compatibility.

# Note that the version of Babel run here should be consistent with
# the version of the runtime Babel which is used in compiled bHYPRE
# code.  Here is how I get to the public version of Babel on the Casc
# network.  As of December 2002, it is consistent with runtime version
# 0.7.5, which is packaged with bHYPRE.  alias babel
# /usr/casc/babel/babel-0.7.4/casc-linux-gcc2.96/bin/babel setenv
# BABEL /usr/casc/babel/babel-0.7.4/casc-linux-gcc2.96/ setenv
# BABEL_EXEC ${BABEL} setenv LD_LIBRARY_PATH
# /usr/casc/babel/babel-0.7.4/casc-linux-gcc2.96/lib:${LD_LIBRARY_PATH}
# As of January 2002, I have switched to babel-0.8.0, which is not yet
# in /usr/casc/babel.

babel --output-directory=bHYPRE -sC Interfaces.idl
babel --output-directory=bHYPREClient-C -cC Interfaces.idl
babel --output-directory=bHYPREClient-F -cF77 Interfaces.idl
