#!/bin/sh
#BHEADER***********************************************************************
# (c) 1998   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision$
#EHEADER***********************************************************************

#==============================================================================
# Environment variables
# NOTE: this should be stripped down to something more minimal
#==============================================================================

CVSROOT=/home/casc/repository
export CVSROOT

PATH=/home/casc/bin:\
/opt/SUNWspro/bin:/usr/ccs/bin:/usr/local/bin:\
/usr/sbin:/usr/bin:/usr/ucb:\
/sbin/bin:\
/usr/local/scripts:\
/usr/local/mpi/mpich/bin
export PATH

#==============================================================================
# Set autotest directories
#==============================================================================

HYPRE_AUTOTEST_DIR="/home/casc/software/hypre/autotest"

#=============================================================================
# Remove old autotest and create new directory
#=============================================================================

if [ -d $HYPRE_AUTOTEST_DIR ]
then
	rm -fR $HYPRE_AUTOTEST_DIR
fi

mkdir $HYPRE_AUTOTEST_DIR
cd $HYPRE_AUTOTEST_DIR
	
#=============================================================================
# Checks out repository, builds and installs in the AUTOTEST directory
#=============================================================================

if [ ! -d "$CVSROOT" ]
then
	echo "Error: no CVS repository, CVSROOT = $CVSROOT"
	exit
fi

cvs checkout -P linear_solvers

cd linear_solvers
./configure
make

#=============================================================================
# Run script to test all driver programs 
#=============================================================================

cd test
./test_drivers.sh

#==============================================================================
# Set permissions so that all developers can access
#  -- give everyone read and execute permission
#  -- give group write permissions
#==============================================================================

echo "setting permissions...."
chmod -fR a+rX,ug+w $HYPRE_AUTOTEST_DIR

