#!/bin/sh
#BHEADER***********************************************************************
# (c) 1998   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision$
#EHEADER***********************************************************************

#==============================================================================
# This script should be scheduled to run automatically some time after
# the 'autotest' script is scheduled to run.  It "checks up" on the
# autotest script to ensure that it has finished running.  If it has
# not, an email is sent out.
#
# The mechanism used to do this is simple.  The autotest script creates
# a special file when it finishes running.  This script just checks for
# the presence of this file.
#==============================================================================

. ./autotest_env

#==============================================================================
# Autotest completion check:
#==============================================================================

RECIPIENTS="\
 rfalgout@llnl.gov\
 cleary1@llnl.gov\
 treadway1@llnl.gov"

HYPRE_MAIL=/usr/ucb/Mail

if [ ! -f "$HYPRE_AUTOTEST_DIR/autotest_finished" ]
then
    ${HYPRE_MAIL} -s "Autotest error: autotest did not finish!" $RECIPIENTS
fi

rm -f $HYPRE_AUTOTEST_DIR/autotest_finished
