#!/usr/bin/sh
#BHEADER***********************************************************************
# (c) 1998   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision$
#EHEADER***********************************************************************

perform_test()
{
  echo ""
  echo "======================================================================"
  echo "Running tests on $HYPRE_RUN_MACHINE"
  echo "======================================================================"
  echo ""

  echo "creating new AUTOTEST directory...."
  ssh ${HYPRE_COMPILE_MACHINE} "\
    (\
        rm -fR ${HYPRE_REMOTE_DIR};\
        mkdir ${HYPRE_REMOTE_DIR}\
    )"

  echo "copying new source...."
  scp -r linear_solvers ${HYPRE_COMPILE_MACHINE}:${HYPRE_REMOTE_DIR}

  echo "running autotest...."
  ssh ${HYPRE_COMPILE_MACHINE} "\
    (\
        cd ${HYPRE_REMOTE_DIR};\
	. linear_solvers/test/autotest_env;\
	[ -f linear_solvers/test/env.${HYPRE_ARCH} ] && . linear_solvers/test/env.${HYPRE_ARCH};\
        . linear_solvers/test/autotest_test ${HYPRE_MACHINE_COMMANDS}\
    )"

  echo "save the test results...."
  ssh ${HYPRE_COMPILE_MACHINE} "\
    (\
        cd ${HYPRE_REMOTE_DIR};\
        cd  linear_solvers;\
        tar -cvf autotest.${HYPRE_RUN_MACHINE}.tar test\
    )"

  echo "copying test results to CASC machine..."
  scp -r  ${HYPRE_COMPILE_MACHINE}:${HYPRE_REMOTE_DIR}/linear_solvers/autotest.${HYPRE_RUN_MACHINE}.tar $HYPRE_AUTOTEST_DIR/.

# echo "cleaning up...."
# ssh ${HYPRE_COMPILE_MACHINE} "\
#   (\
#        rm -fR ${HYPRE_REMOTE_DIR}\
#   )"
}

#==============================================================================
# This script is the top-level script used to regression test hypre.
#==============================================================================

OldMask=umask
umask 007
. ./autotest_env

#=============================================================================
# Check out the repository in the HYPRE_AUTOTEST_DIR directory
#=============================================================================

if [ ! -d "$CVSROOT" ]
then
    echo "Error: no CVS repository, CVSROOT = $CVSROOT"
    exit
fi

cd $HYPRE_AUTOTEST_DIR
rm -fR linear_solvers
cvs -q checkout -P linear_solvers 1> $0.checkout.log 2> $0.checkout.err
echo "$HYPRE_CHECKOUT_EMAIL" > $0.checkout.err.email 
#chgrp -fR hypre linear_solvers # should not be needed if cron started
# from hypre group, i.e., make sure to do a newgrp -l hypre; crontab ...

#==============================================================================
# Run test suites on remote machines
#==============================================================================

while [ "$*" != "" ]
do
  case $1 in
    -blue)
        HYPRE_ARCH="blue"
        HYPRE_COMPILE_MACHINE="blue"
        HYPRE_RUN_MACHINE="blue"
        HYPRE_REMOTE_DIR="/usr/apps/hypre/AUTOTEST"
	HYPRE_MACHINE_COMMANDS="-m -a 2 -cf -o 1"
	perform_test
	HYPRE_MACHINE_COMMANDS="-m -a 2 -dcxfy -t 1 -ns"
        shift;;
    -casc)
	HYPRE_MACHINE_COMMANDS="-m -a 2 -dcxfy -t 1 -ns"
        shift;;
    -dec)
        HYPRE_ARCH="dec"
        HYPRE_COMPILE_MACHINE="west"
        HYPRE_RUN_MACHINE="southeast"
        HYPRE_REMOTE_DIR="/usr/gapps/hypre/alphaev56-dec-osf4.0f/AUTOTEST"
	HYPRE_MACHINE_COMMANDS="-m -r $HYPRE_RUN_MACHINE -a 2 -cf -o 1"
	perform_test
	HYPRE_MACHINE_COMMANDS="-m -a 2 -dcxfy -t 1 -ns"
        shift;;
    -lx)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="lx10"
        HYPRE_RUN_MACHINE="lx10"
        HYPRE_REMOTE_DIR="/usr/gapps/hypre/AUTOTEST"
	HYPRE_MACHINE_COMMANDS="-m -a 2 -cf -o 1"
	perform_test
	HYPRE_MACHINE_COMMANDS="-m -a 2 -dcxfy -t 1 -ns"
        shift;;
    -purify)
	HYPRE_MACHINE_COMMANDS="-m -q 2 -a 1 -dcxfy -t 1 -ns"
        shift;;
    -red)
        HYPRE_ARCH="red"
        HYPRE_COMPILE_MACHINE="sasn100"
        HYPRE_RUN_MACHINE="janus"
        HYPRE_REMOTE_DIR="/usr/apps/hypre/AUTOTEST"
	HYPRE_MACHINE_COMMANDS="-m -r $HYPRE_RUN_MACHINE -a 2 -cf -o 1"
	perform_test
	HYPRE_MACHINE_COMMANDS="-m -a 2 -dcxfy -t 1 -ns"
        shift;;
    -tc2k)
        HYPRE_ARCH="dec"
        HYPRE_COMPILE_MACHINE="tckk126"
        HYPRE_RUN_MACHINE="tckk100"
        HYPRE_REMOTE_DIR="/usr/gapps/hypre/alphaev57-dec-osf5.0/AUTOTEST"
	HYPRE_MACHINE_COMMANDS="-m -a 2 -cf -o 1"
	perform_test
	HYPRE_MACHINE_COMMANDS="-m -a 2 -dcxfy -t 1 -ns"
        shift;;
    -tc)
        HYPRE_ARCH="dec"
        HYPRE_COMPILE_MACHINE="tc04"
        HYPRE_RUN_MACHINE="tc10"
        HYPRE_REMOTE_DIR="/usr/gapps/hypre/alphaev56-dec-osf4.0f/AUTOTEST"
	HYPRE_MACHINE_COMMANDS="-m -a 2 -cf -o 1"
	perform_test
	HYPRE_MACHINE_COMMANDS="-m -a 2 -dcxfy -t 1 -ns"
        shift;;
  esac

  HYPRE_ARCH="casc"
  HYPRE_COMPILE_MACHINE="perrin"
  HYPRE_RUN_MACHINE="perrin"
  HYPRE_REMOTE_DIR="/home/casc/software/hypre/autotest"
  ./autotest_test $HYPRE_MACHINE_COMMANDS

done

#==============================================================================
# Autotest completion check: create "autotest finished" file
#==============================================================================

touch $HYPRE_AUTOTEST_DIR/autotest_finished

umask $OldMask
