#!/bin/sh
#BHEADER***********************************************************************
# (c) 1998   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision$
#EHEADER***********************************************************************

TEMP_FILE=HYPRE_headers.tmp
TWRAPPER_FILE=thread_wrappers.c

#===========================================================================
# Create standard interface prototypes
#===========================================================================

mkproto HYPRE*.c > $TEMP_FILE

#===========================================================================
# Create thread wrapper routines
#===========================================================================

cat > $TWRAPPER_FILE <<@

#include "HYPRE_mv.h"
#include "utilities.h"

#ifdef HYPRE_USE_PTHREADS

@

/usr/xpg4/bin/awk -f ../utilities/thread_wrappers.awk \
    < $TEMP_FILE >> $TWRAPPER_FILE

cat >> $TWRAPPER_FILE <<@

#else

/* this is used only to eliminate compiler warnings */
int hypre_empty;

#endif

@

#===========================================================================
# Echo prototypes to stdout and clean up
#===========================================================================

cat <<@

#ifndef HYPRE_NO_PTHREAD_MANGLING

@

/usr/xpg4/bin/awk -f ../utilities/thread_protos.awk < $TEMP_FILE

cat <<@

#endif

@

rm -f $TEMP_FILE

../utilities/protos HYPRE*.c


