#define SIDL_fcomplex__array_create2dCol_m ary_create2dColnu_a7gr0xha137_m
#define sidl_fcomplex__array_create2dcol_m ary_create2dcolnu_a7gr0xha137_m
#define SIDL_FCOMPLEX__ARRAY_CREATE2DCOL_M ARY_CREATE2DCOLNU_A7GR0XHA137_M

#define SIDL_fcomplex__array_create2dRow_m ary_create2dRow0w84vbbl90fb5f_m
#define sidl_fcomplex__array_create2drow_m ary_create2drow0w84vbbl90fb5f_m
#define SIDL_FCOMPLEX__ARRAY_CREATE2DROW_M ARY_CREATE2DROW0W84VBBL90FB5F_M

#define SIDL_fcomplex__array_createCol_m ary_createColrntwhb8rhunnxohw_m
#define sidl_fcomplex__array_createcol_m ary_createcolrntwhb8rhunnxohw_m
#define SIDL_FCOMPLEX__ARRAY_CREATECOL_M ARY_CREATECOLRNTWHB8RHUNNXOHW_M

#define SIDL_fcomplex__array_createRow_m ary_createRowumpp98gavsfmlebm_m
#define sidl_fcomplex__array_createrow_m ary_createrowumpp98gavsfmlebm_m
#define SIDL_FCOMPLEX__ARRAY_CREATEROW_M ARY_CREATEROWUMPP98GAVSFMLEBM_M

#define SIDL_fcomplex__array_deleteRef_m ary_deleteRefckwappc1nseeiqfh_m
#define sidl_fcomplex__array_deleteref_m ary_deleterefckwappc1nseeiqfh_m
#define SIDL_FCOMPLEX__ARRAY_DELETEREF_M ARY_DELETEREFCKWAPPC1NSEEIQFH_M

#define SIDL_fcomplex__array_isColumnOrder_m ary_isColumnOrdero9g8sjcool59_m
#define sidl_fcomplex__array_iscolumnorder_m ary_iscolumnordero9g8sjcool59_m
#define SIDL_FCOMPLEX__ARRAY_ISCOLUMNORDER_M ARY_ISCOLUMNORDERO9G8SJCOOL59_M

#define SIDL_fcomplex__array_isRowOrder_m ary_isRowOrdera41hjkeeazj7pcn_m
#define sidl_fcomplex__array_isroworder_m ary_isrowordera41hjkeeazj7pcn_m
#define SIDL_FCOMPLEX__ARRAY_ISROWORDER_M ARY_ISROWORDERA41HJKEEAZJ7PCN_M

#define SIDL_fcomplex__array_smartCopy_m ary_smartCopyw6fiaq4cwwi3y0ny_m
#define sidl_fcomplex__array_smartcopy_m ary_smartcopyw6fiaq4cwwi3y0ny_m
#define SIDL_FCOMPLEX__ARRAY_SMARTCOPY_M ARY_SMARTCOPYW6FIAQ4CWWI3Y0NY_M

