#define SIDL_double__array_create2dCol_m ary_create2dColo98d1uqpbqj__d_m
#define sidl_double__array_create2dcol_m ary_create2dcolo98d1uqpbqj__d_m
#define SIDL_DOUBLE__ARRAY_CREATE2DCOL_M ARY_CREATE2DCOLO98D1UQPBQJ__D_M

#define SIDL_double__array_create2dRow_m ary_create2dRow0b_ptuwl1mzcpj_m
#define sidl_double__array_create2drow_m ary_create2drow0b_ptuwl1mzcpj_m
#define SIDL_DOUBLE__ARRAY_CREATE2DROW_M ARY_CREATE2DROW0B_PTUWL1MZCPJ_M

#define SIDL_double__array_isColumnOrder_m ary_isColumnOrder1q2jrb9uhvgf_m
#define sidl_double__array_iscolumnorder_m ary_iscolumnorder1q2jrb9uhvgf_m
#define SIDL_DOUBLE__ARRAY_ISCOLUMNORDER_M ARY_ISCOLUMNORDER1Q2JRB9UHVGF_M

