#define SIDL_dcomplex__array_create2dCol_m ary_create2dCol6avhnlybsmb7_h_m
#define sidl_dcomplex__array_create2dcol_m ary_create2dcol6avhnlybsmb7_h_m
#define SIDL_DCOMPLEX__ARRAY_CREATE2DCOL_M ARY_CREATE2DCOL6AVHNLYBSMB7_H_M

#define SIDL_dcomplex__array_create2dRow_m ary_create2dRowf25xzn6nv_t9m9_m
#define sidl_dcomplex__array_create2drow_m ary_create2drowf25xzn6nv_t9m9_m
#define SIDL_DCOMPLEX__ARRAY_CREATE2DROW_M ARY_CREATE2DROWF25XZN6NV_T9M9_M

#define SIDL_dcomplex__array_createCol_m dc_ary_createCol1n2ragq7yq5mw_m
#define sidl_dcomplex__array_createcol_m dc_ary_createcol1n2ragq7yq5mw_m
#define SIDL_DCOMPLEX__ARRAY_CREATECOL_M DC_ARY_CREATECOL1N2RAGQ7YQ5MW_M

#define SIDL_dcomplex__array_createRow_m dc_ary_createRowke8_dssplak_2_m
#define sidl_dcomplex__array_createrow_m dc_ary_createrowke8_dssplak_2_m
#define SIDL_DCOMPLEX__ARRAY_CREATEROW_M DC_ARY_CREATEROWKE8_DSSPLAK_2_M

#define SIDL_dcomplex__array_deleteRef_m dc_ary_deleteRefxa0efhnr646fj_m
#define sidl_dcomplex__array_deleteref_m dc_ary_deleterefxa0efhnr646fj_m
#define SIDL_DCOMPLEX__ARRAY_DELETEREF_M DC_ARY_DELETEREFXA0EFHNR646FJ_M

#define SIDL_dcomplex__array_isColumnOrder_m ary_isColumnOrder8os6575qjjj0_m
#define sidl_dcomplex__array_iscolumnorder_m ary_iscolumnorder8os6575qjjj0_m
#define SIDL_DCOMPLEX__ARRAY_ISCOLUMNORDER_M ARY_ISCOLUMNORDER8OS6575QJJJ0_M

#define SIDL_dcomplex__array_isRowOrder_m d_ary_isRowOrder4be4x5l3wat9o_m
#define sidl_dcomplex__array_isroworder_m d_ary_isroworder4be4x5l3wat9o_m
#define SIDL_DCOMPLEX__ARRAY_ISROWORDER_M D_ARY_ISROWORDER4BE4X5L3WAT9O_M

#define SIDL_dcomplex__array_smartCopy_m dc_ary_smartCopy6qzp56n_y6emm_m
#define sidl_dcomplex__array_smartcopy_m dc_ary_smartcopy6qzp56n_y6emm_m
#define SIDL_DCOMPLEX__ARRAY_SMARTCOPY_M DC_ARY_SMARTCOPY6QZP56N_Y6EMM_M

