
/*** DO NOT EDIT THIS FILE DIRECTLY (use ../config/gen_code.sh to generate) ***/

/******************************************************************************
 * Copyright (c) 1998 Lawrence Livermore National Security, LLC and other
 * HYPRE Project Developers. See the top-level COPYRIGHT file for details.
 *
 * SPDX-License-Identifier: (Apache-2.0 OR MIT)
 ******************************************************************************/

/* Header file for transforming multiprecision functions names */

#ifndef hypre_IJ_HELPERS_MUP_DEF_HEADER
#define hypre_IJ_HELPERS_MUP_DEF_HEADER

#include "_hypre_mup_def.h"

#define GenerateCoordinates HYPRE_FIXEDPRECISION_FUNC ( GenerateCoordinates )
#define GenerateDifConv HYPRE_FIXEDPRECISION_FUNC ( GenerateDifConv )
#define GenerateLaplacian HYPRE_FIXEDPRECISION_FUNC ( GenerateLaplacian )
#define GenerateLaplacian27pt HYPRE_FIXEDPRECISION_FUNC ( GenerateLaplacian27pt )
#define GenerateLaplacian9pt HYPRE_FIXEDPRECISION_FUNC ( GenerateLaplacian9pt )
#define GenerateRSVarDifConv HYPRE_FIXEDPRECISION_FUNC ( GenerateRSVarDifConv )
#define GenerateRotate7pt HYPRE_FIXEDPRECISION_FUNC ( GenerateRotate7pt )
#define GenerateSysLaplacian HYPRE_FIXEDPRECISION_FUNC ( GenerateSysLaplacian )
#define GenerateSysLaplacianVCoef HYPRE_FIXEDPRECISION_FUNC ( GenerateSysLaplacianVCoef )
#define GenerateVarDifConv HYPRE_FIXEDPRECISION_FUNC ( GenerateVarDifConv )

#endif
