#!/bin/sh
#BHEADER***********************************************************************
# (c) 1998   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision$
#EHEADER***********************************************************************

#=============================================================================
# Parse arguments
#=============================================================================

HYPRE_ARCH=""
HYPRE_INSTALL_FLAG=""
HYPRE_CLEAN_FLAG=""
HYPRE_VERYCLEAN_FLAG=""

while [ "$*" != "" ]
do
case $1 in
  -h|-help) 
	echo "$0 [-opt|-dec|-blue|-red] [install|clean|veryclean] "
	echo 
	echo "Where:"
	echo "-opt            CASC Sun cluster with optimization"
	echo "-dec            LC DEC cluster"
	echo "-blue           ASCI Blue-Pacific"
	echo "-red            ASCI Red"
	echo " install        builds and installs"
	echo " clean          cleans temporary build files (i.e., .o)"
	echo " veryclean      cleans everything"
	exit 0;;
  -opt)
	HYPRE_ARCH="opt"
	shift;;
  -dec)
	HYPRE_ARCH="dec"
	shift;;
  -blue)
	HYPRE_ARCH="blue"
	shift;;
  -red)
	HYPRE_ARCH="red"
	shift;;
  install) 
	HYPRE_INSTALL_FLAG=1
	shift;;
  clean)
	HYPRE_CLEAN_FLAG=1
	shift;;
  veryclean)
	HYPRE_CLEAN_FLAG=1
	HYPRE_VERYCLEAN_FLAG=1
	shift;;
  *)
	echo "Unknown option: $1"
	exit;;
esac
done

HYPRE_MAKE_FLAG=""
if [ "$HYPRE_CLEAN_FLAG" = "" ]
then
    HYPRE_MAKE_FLAG=1
fi

#===========================================================================
# Set up various shell variables
#===========================================================================

# SMG shell variables
SMG_MAKEFILE="Makefile"
if [ "$HYPRE_ARCH" ]
then
    SMG_MAKEFILE=$SMG_MAKEFILE.$HYPRE_ARCH
fi

#===========================================================================
# Build the libraries
#===========================================================================

if [ "$HYPRE_MAKE_FLAG" ]
then

    # SMG
    (cd utilities;             make -f $SMG_MAKEFILE)
    (cd struct_matrix_vector;  make -f $SMG_MAKEFILE)
    (cd struct_linear_solvers; make -f $SMG_MAKEFILE)

fi

#===========================================================================
# Clean
#===========================================================================

if [ "$HYPRE_CLEAN_FLAG" ]
then

    # SMG
    (cd utilities;             make -f $SMG_MAKEFILE clean)
    (cd struct_matrix_vector;  make -f $SMG_MAKEFILE clean)
    (cd struct_linear_solvers; make -f $SMG_MAKEFILE clean)

fi

#===========================================================================
# Very Clean
#===========================================================================

if [ "$HYPRE_VERYCLEAN_FLAG" ]
then

    # SMG
    (cd utilities;             make -f $SMG_MAKEFILE veryclean)
    (cd struct_matrix_vector;  make -f $SMG_MAKEFILE veryclean)
    (cd struct_linear_solvers; make -f $SMG_MAKEFILE veryclean)

fi

#===========================================================================
# Install the libraries
#===========================================================================

if [ "$HYPRE_INSTALL_FLAG" ]
then

    # check that HYPRE_INSTALL_DIR is defined
    if [ ! "$HYPRE_INSTALL_DIR" ]
    then
	echo "Error: set the HYPRE_INSTALL_DIR environment variable"
	exit 1
    fi

    # Check that the install directory exists
    if [ ! -d $HYPRE_INSTALL_DIR ]
    then
	echo "Error: HYPRE_INSTALL_DIR=$HYPRE_INSTALL_DIR does not exist"
	exit
    fi

    # create install subdirectories
    (
	cd $HYPRE_INSTALL_DIR
	DIRS="bin docs include lib"
	for i in $DIRS
	do
	    rm -fr $i
	    mkdir $i
	done
    )

    # SMG
    (
	cd utilities
	cp -f memory.h timer.h timing.h $HYPRE_INSTALL_DIR/include
	cp -f *.a $HYPRE_INSTALL_DIR/lib
    )
    (
	cd struct_matrix_vector
	cp -f HYPRE_mv.h hypre_mv.h $HYPRE_INSTALL_DIR/include
	cp -f *.a $HYPRE_INSTALL_DIR/lib
    )
    (
	cd struct_linear_solvers
	cp -f HYPRE_ls.h hypre_ls.h $HYPRE_INSTALL_DIR/include
	cp -f *.a $HYPRE_INSTALL_DIR/lib
    )
fi

