#!/bin/csh -f
#
pushd distributed_matrix
rm *.o
make lib
popd
#
pushd distributed_linear_solvers/pilut
rm *.o
make lib
popd
#
pushd matrix_matrix
rm *.o
make lib
popd
#
pushd PETScMat_linear_solvers/pilut
rm *.o
make lib
popd
#
pushd PETSc_linear_solvers/ParILUT
rm *.o
make lib
popd
#
pushd CI_struct_matrix_vector
rm *.o
make lib
popd
#
pushd CI_struct_linear_solvers
rm *.o
make lib
popd
