#!/bin/ksh
#BHEADER***********************************************************************
# (c) 1998   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision$
#EHEADER***********************************************************************

print_header()
{
  echo ""
  echo "======================================================================"
  echo "Running tests on $HYPRE_RUN_MACHINE"
  echo "======================================================================"
  echo ""
}
perform_test()
{
  if [ "$DEBUGMODE" = "yes" ] ; then
    set -xv
  fi
  print_header
  if [ "${HYPRE_COMPILE_MACHINE}" = "`hostname | sed 's/\..*$//'`" ]
  then
    [ -f linear_solvers/test/AUTOTEST/autotest_env ] && \
      . linear_solvers/test/AUTOTEST/autotest_env;\
    [ -f linear_solvers/test/AUTOTEST/env.${HYPRE_ARCH} ] && \
      . linear_solvers/test/AUTOTEST/env.${HYPRE_ARCH} ${COMPILERSELECT};\
    linear_solvers/test/AUTOTEST/autotest_test \
      ${HYPRE_MACHINE_COMMANDS} -v ${HYPRE_MESSAGE};\
  else
    echo "deleting old AUTOTEST directory...."
    ${SSH_COMMAND} ${HYPRE_COMPILE_MACHINE} "\
    (\
        rm -fR ${HYPRE_REMOTE_DIR}/linear_solvers;\
    )"

    echo "copying new source...."
    if test "${HYPRE_DIST_DIR}" ; then
      scp -pr linear_solvers ${HYPRE_COMPILE_MACHINE}:${HYPRE_REMOTE_DIR}
    else
      ${SCP_COMMAND} -pr linear_solvers ${HYPRE_REMOTE_DIR}
    fi

    echo "scheduling remote autotest...."
    ${SSH_COMMAND} -f ${HYPRE_COMPILE_MACHINE} "\
    (\
      cd ${HYPRE_REMOTE_DIR##*:};\
      . linear_solvers/test/AUTOTEST/autotest_env;\
      [ -f linear_solvers/test/AUTOTEST/env.${HYPRE_ARCH} ] && \
        . linear_solvers/test/AUTOTEST/env.${HYPRE_ARCH} ${COMPILERSELECT};\
      if test "${HYPRE_DIST_DIR}" ; then\
        linear_solvers/test/AUTOTEST/autotest_test \
          ${HYPRE_MACHINE_COMMANDS} -v ${HYPRE_MESSAGE} -p ${HYPRE_DIST_DIR};\
      else\
        linear_solvers/test/AUTOTEST/autotest_test \
            ${HYPRE_MACHINE_COMMANDS} -v ${HYPRE_MESSAGE};\
      fi;\
    chmod -fR a+rX,ug+w,o-w linear_solvers;\
    chgrp -fR hypre linear_solvers;\
      if test "${HYPRE_DIST_DIR}" ; then\
        rm -fR ${HYPRE_DIST_DIR}/linear_solvers ; \
        ${SCP_COMMAND} -pr ${HYPRE_REMOTE_DIR##*:}/linear_solvers ${HYPRE_DIST_DIR};\
      fi;\
    )" 
  fi
  echo "returning to autotest...."
  
}

#=============================================================================
# Function for display of help/usage
#=============================================================================
help () {
  printf "Usage: %s [-nocvs|-rev Rev#] [-automake] [-debug] host [host ... ]\n" $0
  printf "HYPRE autotest script. This is the high level autotest_test wrapper\n"
  printf "script, usually run nightly from cron. This script determines which\n"
  printf "systems autotest_test is to be executed on, and the test options\n"
  printf "to use.\n"
  printf "\n"
  printf "%s\n" "-nocvs    Do perform cvs checkout, use existing"
  printf "          ./linear_solvers/ directory for autotest.\n"
  printf "%s\n" "-rev Rev# Check out revision or tag." 
  printf "%s\n" "-automake Run automake/autoconf."
  printf "host       Host ID or configuration on which autotest is to be run.\n"
  printf "           Valid host IDs are:\n"
  printf "%s\n" "     -achilles CASC Solaris 8, 128.115 subnet"
  printf "%s\n" "     -blue     ASCI Blue, DPCS."
  printf "%s\n" "     -bluemp   ASCI Blue executing OpenMP versions, DPCS."
  printf "%s\n" "     -casc     CASC Solaris 8"
  printf "%s\n" "     -compass  # obsolute"
  printf "%s\n" "     -compassmp# obsolute"
  printf "%s\n" "     -dwbug    Turn on debug mode."
  printf "%s\n" "     -frost    ASCI Frost, DPCS."
  printf "%s\n" "     -frostmp  ASCI Frost executing OpenMP, DPCS."
  printf "%s\n" "     -gps      Compaq gps320 system, DPCS."
  printf "%s\n" "     -gpsmp    Compaq gps320 system, executing OpenMP, DPCS."
  printf "%s\n" "     -lx       # obsolute"
  printf "%s\n" "     -ilx      Intel running Linux."
  printf "%s\n" "     -insure   CASC Linux, executing insure++."
  printf "%s\n" "     -pengra   Intel running Linux, DPCS."
  printf "%s\n" "     -perrin   CASC Solaris 7, 128.115 subnet"
  printf "%s\n" "     -poincare CASC Solaris 7"
  printf "%s\n" "     -purify   CASC Solaris 5.8, executing purify."
  printf "%s\n" "     -purifyo  CASC Solaris 5.7, executing purify."
  printf "%s\n" "     -red      ASCI Red"
  printf "%s\n" "     -sunup    CASC Solaris 9"
  printf "%s\n" "     -riptide  ASCI VIS SGI running IRIX"
  printf "%s\n" "     -tc2k     Compaq TC2K systum, DPCS."
  printf "%s\n" "     -tc2kmp   Compaq TC2K systum, executing OpenMP, DPCS."
  printf "%s\n" "     -tc       # obsolute"
  printf "%s\n" "     -tcmp     # obsolute"
  printf "%s\n" "     -tux71    CASC Intel running RedHat 7 Linux (pgi-4.1)."
  printf "%s\n" "     -tux81    CASC Intel running RedHat 9 Linux."
  printf "%s\n" "     -tux83    CASC Intel running RedHat 7 Linux."
  printf "%s\n" "     -tuxgcc2  Linux running gcc-2.95.3 compilers"
  printf "%s\n" "     -tuxgcc30 Linux running gcc-3.0.4 compilers"
  printf "%s\n" "     -tuxgcc31 Linux running gcc-3.1.1 compilers"
  printf "%s\n" "     -tuxgcc32 Linux running gcc-3.2.2 compilers"
  printf "%s\n" "     -tuxgcc33 Linux running gcc-3.3.x compilers"
  printf "%s\n" "     -tuxpgi   Linux running PGI-4.1 compilers"
  printf "%s\n" "     -tuxabsoftLinux running Absoft-Pro8.0 Fortran 90"
  printf "%s\n" "     -tuxlahey Linux running Lahey Frotran compiler"
  printf "%s\n" "     -tuxintel Linux running Intel-7.0 compilers"
  printf "%s\n" "     -tuxkai   Linux running KAI KCC-4.0f compiler"
  printf "%s\n" "     -vivid    ASCI VIS Intel running RedHat Linux."
  printf "\n"
}

usage ()
{
  printf "usage: $0 [-nocvs|-rev Rev#|-help] [-automake] HostOptions [Hostoptions . . .]\n"
}

#==============================================================================
# This script is the top-level script used to regression test hypre.
#==============================================================================
DEBUGMODE=""
SUBMSG=""
export SUBMSG
AUTOMAKEMODE=""
HYPRE_MESSAGE=""
COMPILERSELECT=""
StartingDir=`pwd`
export AUTOMAKEMODE HYPRE_MESSAGE COMPILERSELECT
# OpenSSH to F-Secure communication for RSA authentication
SSH_COMMAND="ssh -1"
##SCP_COMMAND="scp -q -oProtocol=1"
SCP_COMMAND="cp"

if [ $# -lt 1 ]
then
  usage
  exit 2
fi
case $1 in
    -h|-help) 
        help
        exit;;
    -d|-debug) 
        DEBUGMODE="yes"
        set -xv
        shift;;
esac

OldMask=`umask -S`
umask u=rwx,g=rx,o=rx
if [ -f ./autotest_env ] 
then
  . ./autotest_env
fi
if [ "$1" = "-nocvs" ]
then
  shift
else
#=============================================================================
# Check out the repository in the HYPRE_AUTOTEST_DIR directory
#=============================================================================

  if [ ! -d "$CVSROOT" ]
  then
    echo "Error: no CVS repository, CVSROOT = $CVSROOT"
    exit
  fi

##cd $HOME/hypre
  rm -fR linear_solvers
  if [ "$1" = "-rev" ]
  then
    REV=$2
    shift
    shift
    cvs -q checkout -r $REV -P linear_solvers 1> $0.checkout.log 2> $0.checkout.err
  else
    cvs -q checkout -P linear_solvers 1> $0.checkout.log 2> $0.checkout.err
  fi
  chmod -fR a+rX,u+w,go-w linear_solvers
  chgrp -fR hypre linear_solvers
  echo "$HYPRE_CHECKOUT_EMAIL" > $0.checkout.err.email 
  chmod -f a+rX,u+w,go-w $0.checkout.*
  chgrp -f hypre $0.checkout.*
##if test "${HYPRE_AUTOTEST_DIR}" &&
##   test -d $HYPRE_AUTOTEST_DIR
##then
##  cd $HYPRE_AUTOTEST_DIR
##  rm -fR linear_solvers $0.checkout.*
##  cp -p $StartingDir/$0.checkout.* $HYPRE_AUTOTEST_DIR
##  cp -pr $StartingDir/linear_solvers $HYPRE_AUTOTEST_DIR
##  cd $StartingDir
##fi
fi
if [ "$1" = "-automake" ]
then
##if [ -x linear_solvers/config/bootstrap ] ; then
##  (PATH=$HOME/mnt/`/usr/casc/hypre/config.guess`/bin:$PATH;\
##  cd linear_solvers;\
##  config/bootstrap)
    AUTOMAKEMODE=yes
##fi
  shift
fi
chmod -fR a+rX,u+w,go-w linear_solvers
chgrp -fR hypre linear_solvers

#==============================================================================
# Run test suites on remote machines
#==============================================================================

while [ "$*" != "" ]
do
  HYPRE_DIST_DIR=""
  COMPILERSELECT=""
  case $1 in
    -achilles)
        HYPRE_ARCH="casc"
        HYPRE_COMPILE_MACHINE="achilles"
        HYPRE_RUN_MACHINE="achilles"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/sparc-sun-solaris2.8/AUTOTEST"
	  HYPRE_MACHINE_COMMANDS="-mb 1 -nse 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[Solaris8]'
        if [ "$DEBUGMODE" = "yes" ] ; then
          HYPRE_MACHINE_COMMANDS="-D $HYPRE_MACHINE_COMMANDS"
        fi
## 	print_header
##      ./autotest_test $HYPRE_MACHINE_COMMANDS -v $HYPRE_MESSAGE
  	perform_test
        shift;;
    -automake)
##      if [ -x linear_solvers/config/bootstrap ] ; then
##	  (PATH=$HOME/mnt/`/usr/casc/hypre/config.guess`/bin:$PATH;\
##        cd linear_solvers;\
##        config/bootstrap)
          AUTOMAKEMODE=yes
##      fi
        shift;;
    -blue | -bluemp)
        HYPRE_ARCH="blue"
        HYPRE_COMPILE_MACHINE="blue"
        HYPRE_RUN_MACHINE="blue"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/powerpc-ibm-aix5.1.0.0/AUTOTEST"
        if [ "$1" = "-bluemp" ] ; then
          SUBMSG="from OpenMP"
	  HYPRE_MACHINE_COMMANDS="-mnse 1 -a 1 -cfo 2"
          HYPRE_MESSAGE='SECONDARY[OpenMP-ASCI-Blue]'
        else
	  HYPRE_MACHINE_COMMANDS="-mb 1 -nse 1 -o 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[ASCI-Blue]'
        fi
	perform_test
        shift;;
    -d|-debug) 
        DEBUGMODE="yes"
        set -xv
        shift;;
    -frost | -frostmp)
        HYPRE_ARCH="blue"
        HYPRE_COMPILE_MACHINE="frost"
        HYPRE_RUN_MACHINE="frost"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/powerpcll-ibm-aix5.1.0.0/AUTOTEST"
        if [ "$1" = "-frostmp" ] ; then
          SUBMSG="from OpenMP"
##	  HYPRE_MACHINE_COMMANDS="-mnse 1 -a 1 -cfo 2"
	  HYPRE_MACHINE_COMMANDS="-mnse 1 -a 1 -cfo 2"
          HYPRE_MESSAGE='SECONDARY[OpenMP-ASCI-White]'
        else
##	  HYPRE_MACHINE_COMMANDS="-mb 1 -nse 1 -o 1 -a 2 -cf"
	  HYPRE_MACHINE_COMMANDS="-me 1 -nsb 1 -o 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[ASCI-White]'
        fi
	perform_test
        shift;;
    -casc)
        HYPRE_ARCH="casc"
        HYPRE_COMPILE_MACHINE="achilles"
        HYPRE_RUN_MACHINE="achilles"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/sparc-sun-solaris2.8/AUTOTEST"
	  HYPRE_MACHINE_COMMANDS="-mb 1 -nse 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[Solaris8]'
        if [ "$DEBUGMODE" = "yes" ] ; then
          HYPRE_MACHINE_COMMANDS="-D $HYPRE_MACHINE_COMMANDS"
        fi
   	print_header
        ./autotest_test $HYPRE_MACHINE_COMMANDS -v $HYPRE_MESSAGE
##	perform_test
        shift;;
    -compass | -compassmp) # obsolute
        HYPRE_ARCH="dec"
        HYPRE_COMPILE_MACHINE="west"
        HYPRE_RUN_MACHINE="southeast"
        HYPRE_REMOTE_DIR="/usr/gapps/hypre/alphaev56-dec-osf4.0f/AUTOTEST"
        if [ "$1" = "-compass" ] ; then
	  HYPRE_MACHINE_COMMANDS="-m -r $HYPRE_RUN_MACHINE -o 1 -a 2 -cf"
        else
	  HYPRE_MACHINE_COMMANDS="-m -r $HYPRE_RUN_MACHINE -o 2"
        fi
	perform_test
        shift;;
    -gps | -gpsmp)
        HYPRE_ARCH="dec"
        HYPRE_COMPILE_MACHINE="gps"
        HYPRE_RUN_MACHINE="gps320"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/alphaev68-dec-osf5.1/AUTOTEST"
        if [ "$AUTOMAKEMODE" = "yes" ] ; then
	  HYPRE_MACHINE_COMMANDS="-m -r $HYPRE_RUN_MACHINE -nse 1 -o 1 -a 1 -cfl 1"
          HYPRE_MESSAGE='OTHER[autotest-OSF1V5.1]'
        elif [ "$1" = "-gps" ] ; then
	  HYPRE_MACHINE_COMMANDS="-m -r $HYPRE_RUN_MACHINE -nse 1 -o 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[OSF1V5.1]'
        else
	  HYPRE_MACHINE_COMMANDS="-m -r $HYPRE_RUN_MACHINE -nse 1 -a 1 -cfo 2"
          HYPRE_MESSAGE='SECONDARY[OpenMP-OSF1V5.1]'
        fi
	perform_test
        shift;;
    -h|-help) 
        help
        exit;;
    -ilx)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="ilx"
        HYPRE_RUN_MACHINE="ilx"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/i686-pc-linux-gnu-ilx/AUTOTEST"
	  HYPRE_MACHINE_COMMANDS="-mne 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='OTHER[pgi-4.1]'
	perform_test
        shift;;
    -insure)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux71"
        HYPRE_RUN_MACHINE="tux71"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu/AUTOTEST"
	HYPRE_MACHINE_COMMANDS="-mnsde 1 -a 1 -cf -i 2"
        HYPRE_MESSAGE='PRIMARY[insure++]'
        HYPRE_MACHINE_COMMANDS="$HYPRE_MACHINE_COMMANDS -v $HYPRE_MESSAGE"
## 	print_header
## 	./autotest_test $HYPRE_MACHINE_COMMANDS
        COMPILERSELECT="gcc2"
   	perform_test
        shift;;
    -lx) # obsolute
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="lx01"
        HYPRE_RUN_MACHINE="lx01"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/alphaev67-unknown-linux-gnu/AUTOTEST"
        if [ "$AUTOMAKEMODE" = "yes" ] ; then
  	  HYPRE_MACHINE_COMMANDS="-mnse 1 -a 1 -cfl 2"
          HYPRE_MESSAGE='TEST[automake-gcc-2.96]'
        else
  	  HYPRE_MACHINE_COMMANDS="-mnse 1 -a 2 -cf"
          HYPRE_MESSAGE='OTHER[gcc-2.96]'
        fi
	perform_test
        shift;;
    -nocvs)
        echo "ERROR: -nocvs option MUST be first argument! Quiting..."
        help
        exit;;
    -pengra)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="pengra"
        HYPRE_RUN_MACHINE="pengra"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/i686-pc-linux-gnu-pengra/AUTOTEST"
	  HYPRE_MACHINE_COMMANDS="-mnse 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='OTHER[icc-6.0]'
	perform_test
        shift;;
    -perrin)
        HYPRE_ARCH="casc"
        HYPRE_COMPILE_MACHINE="perrin"
        HYPRE_RUN_MACHINE="perrin"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/sparc-sun-solaris2.7/AUTOTEST"
	HYPRE_MACHINE_COMMANDS="-mb 1 -nrse 1 -l 1 -a 2 -cf"
        HYPRE_MESSAGE='SECONDARY[Solaris7]'
	perform_test
        shift;;
    -poincare)
        HYPRE_ARCH="casc"
        HYPRE_COMPILE_MACHINE="poincare"
        HYPRE_RUN_MACHINE="poincare"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/sparc-sun-solaris2.7/AUTOTEST"
	HYPRE_MACHINE_COMMANDS="-mb 1 -nse 1 -l 1 -a 2 -cf"
        HYPRE_MESSAGE='SECONDARY[Solaris7]'
	perform_test
        shift;;
    -purify1)
        HYPRE_ARCH="casc"
        HYPRE_COMPILE_MACHINE="sunup"
        HYPRE_RUN_MACHINE="sunup"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/sparc-sun-solaris2.9/AUTOTEST"
	HYPRE_MACHINE_COMMANDS="-mnse 1 -a 1 -cfq 2"
        HYPRE_MESSAGE='SECONDARY[purify]'
	perform_test
        shift;;
    -purify0)
        HYPRE_ARCH="casc"
        HYPRE_COMPILE_MACHINE="perrin"
        HYPRE_RUN_MACHINE="perrin"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/sparc-sun-solaris2.7/AUTOTEST"
	HYPRE_MACHINE_COMMANDS="-mnse 1 -a 1 -cfq 2"
        HYPRE_MESSAGE='SECONDARY[purify]'
	perform_test
        shift;;
    -purify)
        HYPRE_ARCH="casc"
        HYPRE_COMPILE_MACHINE="achilles"
        HYPRE_RUN_MACHINE="achilles"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/sparc-sun-solaris2.8/AUTOTEST"
	HYPRE_MACHINE_COMMANDS="-mnse 1 -a 1 -cfq 2"
        HYPRE_MESSAGE='SECONDARY[purify]'
        print_header
        ./autotest_test $HYPRE_MACHINE_COMMANDS -v $HYPRE_MESSAGE
##	perform_test
        shift;;
    -red)
        HYPRE_ARCH="red"
        HYPRE_COMPILE_MACHINE="sasn100"
        HYPRE_RUN_MACHINE="janus"
        HYPRE_REMOTE_DIR="/usr/apps/hypre/AUTOTEST"
	HYPRE_MACHINE_COMMANDS="-m -r $HYPRE_RUN_MACHINE -o 1 -a 2 -cf"
	perform_test
        shift;;
    -rev)
        echo "ERROR: -rev option MUST be first argument! Quiting..."
        help
        exit;;
    -riptide)
        HYPRE_ARCH="sgi"
        HYPRE_COMPILE_MACHINE="riptide"
        HYPRE_RUN_MACHINE="riptide"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/mips-sgi-irix6.5/AUTOTEST"
        if [ "$AUTOMAKEMODE" = "yes" ] ; then
	  HYPRE_MACHINE_COMMANDS="-mne 1 -a 1 -cfl 1"
          HYPRE_MESSAGE='OTHER[automake-IRIX64]'
        else
	  HYPRE_MACHINE_COMMANDS="-mne 1 -a 2 -cf"
          HYPRE_MESSAGE='OTHER[automake-IRIX64]'
        fi
	perform_test
        shift;;
    -sunup)
        HYPRE_ARCH="casc"
        HYPRE_COMPILE_MACHINE="sunup"
        HYPRE_RUN_MACHINE="sunup"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/sparc-sun-solaris2.9/AUTOTEST"
	HYPRE_MACHINE_COMMANDS="-mb 1 -nse 1 -l 1 -a 2 -cf"
        HYPRE_MESSAGE='SECONDARY[Solaris9]'
	perform_test
        shift;;
    -tc2k | -tc2kmp)
        HYPRE_ARCH="dec"
        HYPRE_COMPILE_MACHINE="tckk"
        HYPRE_RUN_MACHINE="tckk"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/alphaev67-dec-osf5.1/AUTOTEST"
        if [ "$AUTOMAKEMODE" = "yes" ] ; then
	  HYPRE_MACHINE_COMMANDS="-mnse 1 -o 1 -a 1 -cfl 1"
          HYPRE_MESSAGE='OTHER[OSF1]'
        elif [ "$1" = "-tc2k" ] ; then
	  HYPRE_MACHINE_COMMANDS="-mnse 1 -o 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[OSF1]'
        else
          SUBMSG="from OpenMP"
	  HYPRE_MACHINE_COMMANDS="-m -o 2"
          HYPRE_MESSAGE='SECONDARY[OpenMP-OSF1]'
        fi
	perform_test
        shift;;
    -tc | -tcmp) # obsolute
        HYPRE_ARCH="dec"
        HYPRE_COMPILE_MACHINE="tc01"
        HYPRE_RUN_MACHINE="tc10"
        HYPRE_REMOTE_DIR="/usr/gapps/hypre/alphaev56-dec-osf5.1/AUTOTEST"
        if [ "$1" = "-tc" ] ; then
	  HYPRE_MACHINE_COMMANDS="-m -o 1 -a 2 -cf"
        else
          SUBMSG="from OpenMP"
	  HYPRE_MACHINE_COMMANDS="-m -o 2"
        fi
	perform_test
        shift;;
    -tux71)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux71"
        HYPRE_RUN_MACHINE="tux71"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu/AUTOTEST"
	  HYPRE_MACHINE_COMMANDS="-mb 1 -nsde 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='PRIMARY[gcc-2.96]'
##      ./autotest_test $HYPRE_MACHINE_COMMANDS -v $HYPRE_MESSAGE
        COMPILERSELECT="gcc2"
	perform_test
        shift;;
    -tuxgcc2)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux83"
        HYPRE_RUN_MACHINE="tux83"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu-gcc3.x/AUTOTEST"
	  HYPRE_MACHINE_COMMANDS="-mb 1 -ndse 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[gcc-2.95.3]'
        COMPILERSELECT="gcc2"
	perform_test
        shift;;
    -tuxgcc30)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux83"
        HYPRE_RUN_MACHINE="tux83"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu-gcc3.x/AUTOTEST"
	  HYPRE_MACHINE_COMMANDS="-mb 1 -ndse 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[gcc-3.0.4]'
        COMPILERSELECT="gcc30"
	perform_test
        shift;;
    -tuxgcc31)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux83"
        HYPRE_RUN_MACHINE="tux83"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu-gcc3.x/AUTOTEST"
	  HYPRE_MACHINE_COMMANDS="-mb 1 -ndse 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[gcc-3.1.1]'
        COMPILERSELECT="gcc31"
	perform_test
        shift;;
    -tuxgcc32)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux83"
        HYPRE_RUN_MACHINE="tux83"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu-gcc3.x/AUTOTEST"
	  HYPRE_MACHINE_COMMANDS="-mb 1 -ndse 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[gcc-3.2.2]'
        COMPILERSELECT="gcc32"
	perform_test
        shift;;
    -tuxgcc33)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux83"
        HYPRE_RUN_MACHINE="tux83"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu-gcc3.x/AUTOTEST"
	  HYPRE_MACHINE_COMMANDS="-mb 1 -ndse 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[gcc-3.3.x]'
        COMPILERSELECT="gcc33"
	perform_test
        shift;;
    -tuxpgi)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux83"
        HYPRE_RUN_MACHINE="tux83"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu-pgi4.x/AUTOTEST"
	  HYPRE_MACHINE_COMMANDS="-mnse 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[pgi-4.1]'
        COMPILERSELECT="pgi"
	perform_test
        shift;;
    -tuxabsoft)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux83"
        HYPRE_RUN_MACHINE="tux83"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu-gcc3.x/AUTOTEST"
	  HYPRE_MACHINE_COMMANDS="-mb 1 -nde 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[Absoft-Pro8.0]'
        COMPILERSELECT="absoft"
	perform_test
        shift;;
    -tuxlahey)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux83"
        HYPRE_RUN_MACHINE="tux83"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu-gcc3.x/AUTOTEST"
	  HYPRE_MACHINE_COMMANDS="-mb 1 -nde 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[lahey]'
        COMPILERSELECT="lahey"
	perform_test
        shift;;
    -tuxintel)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux83"
        HYPRE_RUN_MACHINE="tux83"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu-gcc3.x/AUTOTEST"
	  HYPRE_MACHINE_COMMANDS="-mb 1 -nde 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[Intel-7.0]'
        COMPILERSELECT="intel"
	perform_test
        shift;;
    -tuxkai)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux83"
        HYPRE_RUN_MACHINE="tux83"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu-gcc3.x/AUTOTEST"
	  HYPRE_MACHINE_COMMANDS="-mb 1 -nde 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[KCC-4.0f]'
        COMPILERSELECT="kai"
	perform_test
        shift;;
    -tux81)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux81"
        HYPRE_RUN_MACHINE="tux81"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu-redhat8/AUTOTEST"
	  HYPRE_MACHINE_COMMANDS="-mnse 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[redhat8-gcc-3.2.3]'
##      ./autotest_test $HYPRE_MACHINE_COMMANDS -v $HYPRE_MESSAGE
        COMPILERSELECT="default"
	perform_test
        shift;;
    -tux83)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux83"
        HYPRE_RUN_MACHINE="tux83"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu-pgi4.x/AUTOTEST"
	  HYPRE_MACHINE_COMMANDS="-mnse 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[pgi-4.1]'
##      ./autotest_test $HYPRE_MACHINE_COMMANDS -v $HYPRE_MESSAGE
        COMPILERSELECT="pgi"
	perform_test
        shift;;
    -tux149)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux149"
        HYPRE_RUN_MACHINE="tux149"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu/AUTOTEST"
	  HYPRE_MACHINE_COMMANDS="-mnse 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[pgi-4.1]'
        ./autotest_test $HYPRE_MACHINE_COMMANDS -v $HYPRE_MESSAGE
#       COMPILERSELECT="default"
#	perform_test
        shift;;
    -vivid)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="vivid"
        HYPRE_RUN_MACHINE="vivid"
        HYPRE_REMOTE_DIR="vivid:/usr/gapps/hypre/i686-pc-linux-gnu-vivid/AUTOTEST"
	  HYPRE_MACHINE_COMMANDS="-mne 1 -l 1 -a 2 -cf"
          HYPRE_MESSAGE='OTHER'
        SCP_COMMAND="scp -q"
	perform_test
        SCP_COMMAND="cp"
        shift;;
    *)
        shift;;
  esac


done

#==============================================================================
# Autotest completion check: create "autotest finished" file
#==============================================================================

#touch $HYPRE_AUTOTEST_DIR/autotest_finished
chmod -fR a+rX,u+w,go-w linear_solvers
chgrp -fR hypre linear_solvers

umask $OldMask
