#!/bin/sh
#BHEADER**********************************************************************
# Copyright (c) 2006   The Regents of the University of California.
# Produced at the Lawrence Livermore National Laboratory.
# Written by the HYPRE team <hypre-users@llnl.gov>, UCRL-CODE-222953.
# All rights reserved.
#
# This file is part of HYPRE (see http://www.llnl.gov/CASC/hypre/).
# Please see the COPYRIGHT_and_LICENSE file for the copyright notice, 
# disclaimer and the GNU Lesser General Public License.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License (as published by the Free
# Software Foundation) version 2.1 dated February 1999.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the IMPLIED WARRANTY OF MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the terms and conditions of the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
# $Revision$
#EHEADER**********************************************************************


#==============================================================================
# Environment variables
# NOTE: this should be stripped down to something more minimal
#==============================================================================

CVSROOT=/home/casc/repository
export CVSROOT

PATH=/bin:/usr/bin:/sbin:/usr/sbin
PATH=${PATH}:/usr/X11R6/bin:/usr/local/bin:/usr/apps/bin
export PATH

#==============================================================================
# Set autotest directory to current directory
#==============================================================================

HYPRE_AUTOTEST_DIR=`pwd`
export HYPRE_AUTOTEST_DIR

#==============================================================================
# Email lists
#==============================================================================

HYPRE_DEFAULT_EMAIL="\
 rfalgout@llnl.gov\
 hill66@llnl.gov"

HYPRE_ALL_EMAIL="$HYPRE_DEFAULT_EMAIL\
 abaker@llnl.gov\
 painter1@llnl.gov\
 lee123@llnl.gov\
 kolev1@llnl.gov\
 yang11@llnl.gov\
 vhenson@llnl.gov\
 chtong@llnl.gov"

export HYPRE_DEFAULT_EMAIL HYPRE_ALL_EMAIL
