#!/bin/sh
#BHEADER***********************************************************************
# (c) 1998   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision$
#EHEADER***********************************************************************

print_header()
{
  echo ""
  echo "======================================================================"
  echo "Running tests on $HYPRE_RUN_MACHINE"
  echo "======================================================================"
  echo ""
}

perform_test()
{
  if [ "$DEBUGMODE" = "yes" ] ; then
    set -xv
  fi
  print_header
  if [ "${HYPRE_COMPILE_MACHINE}" = "`hostname | sed 's/\..*$//'`" ]
  then
    [ -f linear_solvers/test/AUTOTEST/autotest_env ] && \
      . linear_solvers/test/AUTOTEST/autotest_env;\
    [ -f linear_solvers/test/AUTOTEST/env.${HYPRE_ARCH} ] && \
      . linear_solvers/test/AUTOTEST/env.${HYPRE_ARCH} ${COMPILERSELECT};\
    linear_solvers/test/AUTOTEST/autotest_test \
      ${HYPRE_MACHINE_COMMANDS} -v ${HYPRE_MESSAGE};\
  else
    echo "deleting old AUTOTEST directory...."
    ${SSH_COMMAND} ${HYPRE_COMPILE_MACHINE} "\
    (/bin/sh -c \"\
        rm -fR ${HYPRE_REMOTE_DIR}/linear_solvers;\"\
    )"

    echo "copying new source...."
    if test "${HYPRE_DIST_DIR}" ; then
      scp -qpr linear_solvers ${HYPRE_COMPILE_MACHINE}:${HYPRE_REMOTE_DIR}
    else
      ${SCP_COMMAND} -pr linear_solvers ${HYPRE_REMOTE_DIR}
    fi

    echo "scheduling remote autotest...."
    ${SSH_COMMAND} -f ${HYPRE_COMPILE_MACHINE} "\
    (/bin/sh -c \"\
      cd ${HYPRE_REMOTE_DIR##*:};\
      . linear_solvers/test/AUTOTEST/autotest_env;\
      [ -f linear_solvers/test/AUTOTEST/env.${HYPRE_ARCH} ] && \
        . linear_solvers/test/AUTOTEST/env.${HYPRE_ARCH} ${COMPILERSELECT};\
      if test "${HYPRE_DIST_DIR}" ; then\
        linear_solvers/test/AUTOTEST/autotest_test \
          ${HYPRE_MACHINE_COMMANDS} -v ${HYPRE_MESSAGE} -p ${HYPRE_DIST_DIR};\
      else\
        linear_solvers/test/AUTOTEST/autotest_test \
            ${HYPRE_MACHINE_COMMANDS} -v ${HYPRE_MESSAGE};\
      fi;\
    chmod -fR a+rX,ug+w,o-w linear_solvers;\
    chgrp -fR hypre linear_solvers;\
      if test "${HYPRE_DIST_DIR}" ; then\
        rm -fR ${HYPRE_DIST_DIR}/linear_solvers ; \
        ${SCP_COMMAND} -pr ${HYPRE_REMOTE_DIR##*:}/linear_solvers ${HYPRE_DIST_DIR};\
      fi;\"\
    )" 
  fi
  echo "returning to autotest...."
  
}

#=============================================================================
# Function for display of help/usage
#=============================================================================
help () {
  printf "Usage: %s [-nocvs|-rev Rev#] [-debug] host [host ... ]\n" $0
  printf "\n"
  printf "HYPRE autotest script. This is the high level wrapper for the\n"
  printf "autotest_test script, which is run nightly from cron. This script\n"
  printf "determines which systems autotest_test is to be executed on, and the\n"
  printf "options to use.\n"
  printf "\n"
  printf "%s\n" "-nocvs    Do not checkout the latest source code from CVS.\n"
  printf "                 Use the existing ./linear_solvers/ directory for testing.\n"
  printf "%s\n" "-rev Rev# Check out the specified revision or tagged source from CVS.\n" 
  printf "host   Host ID or configuration on which autotest is to be run.\n"
  printf "       Valid host IDs are:\n"
  printf "%s\n" "     -debug    Turn on debug mode."
  printf "%s\n" "     -frost    ASCI Frost, DPCS."
  printf "%s\n" "     -frostmp  ASCI Frost executing OpenMP, DPCS."
  printf "%s\n" "     -gps      Compaq gps320 system, DPCS."
  printf "%s\n" "     -gpsmp    Compaq gps320 system, executing OpenMP, DPCS."
  printf "%s\n" "     -ilx      Intel running Linux."
  printf "%s\n" "     -insure   CASC Linux, executing insure++."
  printf "%s\n" "     -mcr      Intel Linux, CHAOS2."
  printf "%s\n" "     -pengra   Intel Linux, CHAOS2."
  printf "%s\n" "     -red      ASCI Red"
  printf "%s\n" "     -tux149   CASC running RedHat Enterprise Linux."
  printf "%s\n" "     -tuxgcc   CASC running latest gcc compilers"
  printf "%s\n" "     -tuxpgi   CASC running latest PGI compilers"
  printf "%s\n" "     -tuxabsoftCASC running Absoft-Pro8.0 Fortran 90"
  printf "%s\n" "     -tuxlahey CASC running Lahey Frotran compiler"
  printf "%s\n" "     -tuxintel CASC running Intel-8.0 compilers"
  printf "%s\n" "     -tuxkai   CASC running latest KAI KCC compiler"
  printf "\n"
}

usage ()
{
  printf "usage: $0 [-nocvs|-rev Rev#|-help] HostOptions [Hostoptions . . .]\n"
}

#==============================================================================
# This script is the top-level script used to regression test hypre.
#==============================================================================
DEBUGMODE=""
HYPRE_MESSAGE=""
COMPILERSELECT=""
StartingDir=`pwd`
export HYPRE_MESSAGE COMPILERSELECT

# OpenSSH to F-Secure communication for RSA authentication
SSH_COMMAND="ssh"

##SCP_COMMAND="scp -q -oProtocol=1"
SCP_COMMAND="cp"

if [ $# -lt 1 ]
then
  usage
  exit 2
fi
case $1 in
    -h|-help) 
        help
        exit;;
    -d|-debug) 
        DEBUGMODE="yes"
        set -xv
        shift;;
esac

OldMask=`umask -S`
umask u=rwx,g=rx,o=rx

if [ -f ./autotest_env ] 
then
  . ./autotest_env
fi

if [ "$1" = "-nocvs" ]
then
  shift
else
#=============================================================================
# Check out the repository into the HYPRE_AUTOTEST_DIR directory
#=============================================================================

  if [ ! -d "$CVSROOT" ]
  then
    echo "Error: no CVS repository, CVSROOT = $CVSROOT"
    exit
  fi

##              remove existing linear_solvers directory then checkout
##              requested version
  rm -fR linear_solvers
  if [ "$1" = "-rev" ]
  then
    REV=$2
    shift
    shift
    cvs -q checkout -r $REV -P linear_solvers 1> $0.checkout.log 2> $0.checkout.err
  else
    cvs -q checkout -P linear_solvers 1> $0.checkout.log 2> $0.checkout.err
  fi
  chmod -fR a+rX,u+w,go-w linear_solvers
  chgrp -fR hypre linear_solvers
  echo "$HYPRE_CHECKOUT_EMAIL" > $0.checkout.err.email 
  chmod -f a+rX,u+w,go-w $0.checkout.*
  chgrp -f hypre $0.checkout.*
fi

chmod -fR a+rX,u+w,go-w linear_solvers
chgrp -fR hypre linear_solvers

#==============================================================================
# Run test suites on remote machines
#==============================================================================

while [ "$*" != "" ]
do
  HYPRE_DIST_DIR=""
  COMPILERSELECT=""
  case $1 in
    -d|-debug) 
        DEBUGMODE="yes"
        set -xv
        shift;;
    -frost | -frostmp)
        HYPRE_ARCH="frost"
        HYPRE_COMPILE_MACHINE="frost"
        HYPRE_RUN_MACHINE="frost"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/powerpcll-ibm-aix5.1.0.0/AUTOTEST"
        if [ "$1" = "-frostmp" ] ; then
	  HYPRE_MACHINE_COMMANDS="-mnse 1 -a 1 -cfo 2"
          HYPRE_MESSAGE='SECONDARY[OpenMP-Frost]'
        else
	  HYPRE_MACHINE_COMMANDS="-me 1 -nsb 1 -o 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[Frost]'
        fi
	perform_test
        shift;;
    -gps | -gpsmp)
        HYPRE_ARCH="dec"
        HYPRE_COMPILE_MACHINE="gps"
        HYPRE_RUN_MACHINE="gps320"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/alphaev68-dec-osf5.1/AUTOTEST"
        if [ "$1" = "-gps" ] ; then
	  HYPRE_MACHINE_COMMANDS="-m -r $HYPRE_RUN_MACHINE -nse 1 -o 1 -a 2 -cf"
          HYPRE_MESSAGE='SECONDARY[GPS]'
        else
	  HYPRE_MACHINE_COMMANDS="-m -r $HYPRE_RUN_MACHINE -nse 1 -a 1 -cfo 2"
          HYPRE_MESSAGE='SECONDARY[OpenMP-GPS]'
        fi
	perform_test
        shift;;
    -h|-help) 
        help
        exit;;
    -ilx)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="ilx"
        HYPRE_RUN_MACHINE="ilx"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/i686-pc-linux-gnu-ilx/AUTOTEST"
	HYPRE_MACHINE_COMMANDS="-mne 1 -a 2 -cf"
        HYPRE_MESSAGE='SECONDARY[ILX]'
	perform_test
        shift;;
    -insure)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux149"
        HYPRE_RUN_MACHINE="tux149"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu/AUTOTEST"
	HYPRE_MACHINE_COMMANDS="-mnsde 1 -a 1 -cf -i 2"
        HYPRE_MESSAGE='PRIMARY[insure++]'
        HYPRE_MACHINE_COMMANDS="$HYPRE_MACHINE_COMMANDS -v $HYPRE_MESSAGE"
        COMPILERSELECT="gcc"
   	perform_test
        shift;;
    -mcr)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="mcr"
        HYPRE_RUN_MACHINE="mcr"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/i686-pc-linux-gnu-chaos2/AUTOTEST"
        HYPRE_MACHINE_COMMANDS="-mnse 1 -a 2 -cf"
        HYPRE_MESSAGE='SECONDARY[MCR]'
	perform_test
        shift;;
    -nocvs)
        echo "ERROR: -nocvs option MUST be first argument! Quiting..."
        help
        exit;;
    -pengra)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="pengra"
        HYPRE_RUN_MACHINE="pengra"
        HYPRE_REMOTE_DIR="/usr/casc/hypre/i686-pc-linux-gnu-chaos2/AUTOTEST"
        HYPRE_MACHINE_COMMANDS="-mnse 1 -a 2 -cf"
        HYPRE_MESSAGE='SECONDARY[Pengra]'
	perform_test
        shift;;
    -red)
        HYPRE_ARCH="red"
        HYPRE_COMPILE_MACHINE="sasn100"
        HYPRE_RUN_MACHINE="janus"
        HYPRE_REMOTE_DIR="/usr/apps/hypre/AUTOTEST"
	HYPRE_MACHINE_COMMANDS="-m -r $HYPRE_RUN_MACHINE -o 1 -a 2 -cf"
        HYPRE_MESSAGE='OTHER[RED]'
	perform_test
        shift;;
    -rev)
        echo "ERROR: -rev option MUST be first argument! Quiting..."
        help
        exit;;
    -tux149)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux149"
        HYPRE_RUN_MACHINE="tux149"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu/AUTOTEST"
        HYPRE_MACHINE_COMMANDS="-mb 1 -nsde 1 -a 2 -cf"
        HYPRE_MESSAGE='PRIMARY[default]'
        COMPILERSELECT="default"
	perform_test
        shift;;
    -tuxlocal)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux149"
        HYPRE_RUN_MACHINE="tux149"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu/AUTOTEST"
        HYPRE_MACHINE_COMMANDS="-mndse 1 -a 2 -cf"
        HYPRE_MESSAGE='LOCAL TEST[default]'
        COMPILERSELECT="default"
        ./autotest_test $HYPRE_MACHINE_COMMANDS -v $HYPRE_MESSAGE
        shift;;
    -tuxpgi)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux149"
        HYPRE_RUN_MACHINE="tux149"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu-pgi5.x/AUTOTEST"
        HYPRE_MACHINE_COMMANDS="-mndse 1 -a 2 -cf"
        HYPRE_MESSAGE='SECONDARY[pgi]'
        COMPILERSELECT="pgi"
	perform_test
        shift;;
    -tuxabsoft)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux149"
        HYPRE_RUN_MACHINE="tux149"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu-gcc3.x/AUTOTEST"
        HYPRE_MACHINE_COMMANDS="-mb 1 -nde 1 -a 2 -cf"
        HYPRE_MESSAGE='SECONDARY[Absoft-Pro8.0]'
        COMPILERSELECT="absoft"
	perform_test
        shift;;
    -tuxlahey)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux149"
        HYPRE_RUN_MACHINE="tux149"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu-gcc3.x/AUTOTEST"
        HYPRE_MACHINE_COMMANDS="-mb 1 -nde 1 -a 2 -cf"
        HYPRE_MESSAGE='SECONDARY[lahey]'
        COMPILERSELECT="lahey"
	perform_test
        shift;;
    -tuxintel)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux149"
        HYPRE_RUN_MACHINE="tux149"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu-gcc3.x/AUTOTEST"
        HYPRE_MACHINE_COMMANDS="-mb 1 -nde 1 -a 2 -cf"
        HYPRE_MESSAGE='SECONDARY[Intel-8.0]'
        COMPILERSELECT="intel"
	perform_test
        shift;;
    -tuxkai)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="tux149"
        HYPRE_RUN_MACHINE="tux149"
        HYPRE_REMOTE_DIR="/usr/tmp"
        HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu-kai/AUTOTEST"
	HYPRE_MACHINE_COMMANDS="-mb 1 -nde 1 -a 2 -cf"
        HYPRE_MESSAGE='SECONDARY[KCC]'
        COMPILERSELECT="kai"
	perform_test
        shift;;
    -vivid)
        HYPRE_ARCH="linux"
        HYPRE_COMPILE_MACHINE="vivid"
        HYPRE_RUN_MACHINE="vivid"
        HYPRE_REMOTE_DIR="vivid:/usr/gapps/hypre/i686-pc-linux-gnu-vivid/AUTOTEST"
        HYPRE_MACHINE_COMMANDS="-mne 1 -a 2 -cf"
        HYPRE_MESSAGE='OTHER[VIVID]'
        SCP_COMMAND="scp -q"
	perform_test
        SCP_COMMAND="cp"
        shift;;
    *)
        shift;;
  esac


done

#==============================================================================
#     07/29/04 -- emh
#     Build documents in directory:
#        /usr/casc/hypre/i686-pc-linux-gnu/AUTOTEST/linear_solvers/docs
#     so that the latest autotested docs are accessible through the HYPRE 
#     internal website
#==============================================================================
HYPRE_ARCH="linux"
HYPRE_COMPILE_MACHINE="tux149"
HYPRE_RUN_MACHINE="tux149"
HYPRE_REMOTE_DIR="/usr/tmp"
HYPRE_DIST_DIR="/usr/casc/hypre/i686-pc-linux-gnu/AUTOTEST"
HYPRE_MACHINE_COMMANDS=" -a 1 -d"
HYPRE_MESSAGE='SECONDARY[Building Docs Only]'
COMPILERSELECT="default"
./autotest_test $HYPRE_MACHINE_COMMANDS -v $HYPRE_MESSAGE

#==============================================================================
# Set permissions
#==============================================================================

chmod -fR a+rX,ug+w,o-w linear_solvers
chgrp -fR hypre linear_solvers

umask $OldMask
