#!/bin/sh
#BHEADER**********************************************************************
# Copyright (c) 2006   The Regents of the University of California.
# Produced at the Lawrence Livermore National Laboratory.
# Written by the HYPRE team <hypre-users@llnl.gov>, UCRL-CODE-222953.
# All rights reserved.
#
# This file is part of HYPRE (see http://www.llnl.gov/CASC/hypre/).
# Please see the COPYRIGHT_and_LICENSE file for the copyright notice, 
# disclaimer and the GNU Lesser General Public License.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License (as published by the Free
# Software Foundation) version 2.1 dated February 1999.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the IMPLIED WARRANTY OF MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the terms and conditions of the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
# $Revision$
#EHEADER**********************************************************************


#==============================================================================
# This script should be scheduled to run automatically some time after
# the 'autotest' script is scheduled to run.  It "checks up" on the
# autotest script to ensure that it has finished running.  If it has
# not, an email is sent out.
#
# The mechanism used to do this is simple.  The autotest script creates
# a special file when it finishes running.  This script just checks for
# the presence of this file.
#==============================================================================

. ./autotest_env

#==============================================================================
# Autotest completion check:
#==============================================================================

RECIPIENTS="\
 rfalgout@llnl.gov\
 hill66@llnl.gov"

HYPRE_MAIL=/usr/bin/mailx

if [ ! -f "$HYPRE_AUTOTEST_DIR/autotest_finished" ]
then
    ${HYPRE_MAIL} -s "Autotest error: autotest did not finish!" $RECIPIENTS
fi

rm -f $HYPRE_AUTOTEST_DIR/autotest_finished
