#!/bin/sh
#BHEADER***********************************************************************
# (c) 1999   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision$
#EHEADER***********************************************************************

#==============================================================================
# Environment variables
# NOTE: this should be stripped down to something more minimal
#==============================================================================

CVSROOT=/home/casc/repository
export CVSROOT

##PATH=/usr/xpg4/bin:/opt/SUNWspro/bin:/usr/bin:/bin # Solaris version
PATH=/bin:/usr/bin:/sbin:/usr/sbin                # Linux version
PATH=${PATH}:/usr/X11R6/bin:/usr/local/bin:/usr/apps/bin
export PATH

#==============================================================================
# Set autotest directory to current directory
#==============================================================================

HYPRE_AUTOTEST_DIR=`pwd`
export HYPRE_AUTOTEST_DIR

#==============================================================================
# Email lists
#==============================================================================

if [ -z "$NO_HYPRE_MAIL" -o "$NO_HYPRE_MAIL" = "" ] ; then
HYPRE_DEFAULT_EMAIL="\
 rfalgout@llnl.gov\
 hill66@llnl.gov"

HYPRE_CHECKOUT_EMAIL="$HYPRE_DEFAULT_EMAIL"

HYPRE_CONFIGURE_EMAIL="$HYPRE_DEFAULT_EMAIL"

HYPRE_STRUCT_EMAIL="$HYPRE_DEFAULT_EMAIL\
 jones97@llnl.gov\
 painter1@llnl.gov\
 lee123@llnl.gov"

HYPRE_IJ_EMAIL="$HYPRE_DEFAULT_EMAIL\
 painter1@llnl.gov\
 jones97@llnl.gov\
 yang11@llnl.gov\
 vhenson@llnl.gov\
 chow8@llnl.gov\
 chtong@llnl.gov"

HYPRE_FEI_EMAIL="$HYPRE_DEFAULT_EMAIL\
 chow8@llnl.gov\
 chtong@llnl.gov"

HYPRE_ALL_EMAIL="$HYPRE_DEFAULT_EMAIL\
 painter1@llnl.gov\
 lee123@llnl.gov\
 jones97@llnl.gov\
 yang11@llnl.gov\
 vhenson@llnl.gov\
 chow8@llnl.gov\
 chtong@llnl.gov"
else
HYPRE_DEFAULT_EMAIL=""
HYPRE_CHECKOUT_EMAIL="$HYPRE_DEFAULT_EMAIL"
HYPRE_CONFIGURE_EMAIL="$HYPRE_DEFAULT_EMAIL"
HYPRE_STRUCT_EMAIL="$HYPRE_DEFAULT_EMAIL"
HYPRE_IJ_EMAIL="$HYPRE_DEFAULT_EMAIL"
HYPRE_FEI_EMAIL="$HYPRE_DEFAULT_EMAIL"
HYPRE_ALL_EMAIL="$HYPRE_DEFAULT_EMAIL"
fi

export HYPRE_DEFAULT_EMAIL HYPRE_CHECKOUT_EMAIL HYPRE_CONFIGURE_EMAIL
export HYPRE_STRUCT_EMAIL HYPRE_IJ_EMAIL HYPRE_FEI_EMAIL
export HYPRE_ALL_EMAIL
