# LaTeX2HTML 96.1-g (June 11, 1996)
# Associate images original text with physical files.

$key = q/{_inline}$langlefloatrangle${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=53 HEIGHT=29 ALIGN=MIDDLE  SRC="img41.gif"  > |; 
$key = q/{tabular}ll0;SPMamp;nooutput(default)1;SPMamp;matrixstatistics(includesinformationoninterpolationoperatorsand;SPMamp;matricesgeneratedoneachlevel)2;SPMamp;cyclestatistics(includesresidualsgeneratedduringsolvephase)3;SPMamp;matrixandcyclestatistics{tabular}/;
$cached_env_img{$key} = q| <IMG WIDTH=580 HEIGHT=108 ALIGN=BOTTOM  SRC="img24.gif"  > |; 
$key = q/{figure}centeringincludegraphics[width=5in]concep_iface.epslabelfig-conceptual-interface{figure}/;
$cached_env_img{$key} = q| <IMG WIDTH=598 HEIGHT=330 ALIGN=BOTTOM  SRC="img1.gif"  > |; 
$key = q/{_inline}$0leitnlevels${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=82 HEIGHT=27 ALIGN=MIDDLE  SRC="img26.gif"  > |; 
$key = q/{_inline}$ttfilter=-0.9${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=116 HEIGHT=22 ALIGN=MIDDLE  SRC="img38.gif"  > |; 
$key = q/{figure}[t]centeringincludegraphics[width=4in]block_structured.epslabelfig-block-structured-grid{figure}/;
$cached_env_img{$key} = q| <IMG WIDTH=478 HEIGHT=436 ALIGN=BOTTOM  SRC="img9.gif"  > |; 
$key = q/{_inline}$-a_i,jgeqthetamax_jneqi-a_ij${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=156 HEIGHT=27 ALIGN=MIDDLE  SRC="img20.gif"  > |; 
$key = q/{_inline}$ttthresh=-0.9${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=116 HEIGHT=22 ALIGN=MIDDLE  SRC="img35.gif"  > |; 
$key = q/{_inline}$itnlevels=1${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=83 HEIGHT=13 ALIGN=BOTTOM  SRC="img28.gif"  > |; 
$key = q/{_inline}$langleintrangle${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=35 HEIGHT=29 ALIGN=MIDDLE  SRC="img40.gif"  > |; 
$key = q/{_inline}$A_p${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=19 HEIGHT=26 ALIGN=MIDDLE  SRC="img15.gif"  > |; 
$key = q/{_inline}$10^-7${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=34 HEIGHT=15 ALIGN=BOTTOM  SRC="img19.gif"  > |; 
$key = q/{_inline}$|b~-~Ax^(n)|_2|b|_2leq${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=172 HEIGHT=33 ALIGN=MIDDLE  SRC="img18.gif"  > |; 
$key = q/{table}[h]centertabular|l|p4.5in|hlineParameterName;SPMamp;ParameterValueshlinehlinesolver;SPMamp;codecg,codegmres(default),codebicgstab,codetfqmr,codeboomeramg,codesuperlu,codesuperluxpreconditioner;SPMamp;codediagonal(default),codepilut,codeparasails,codeboomeramg,codeeuclidgmresDim;SPMamp;anintegerspecifyingthevalueofcodeminrestartedGMRES(m).Thedefaultvalueis50.maxIterations;SPMamp;anintegerspecifyingthemaximumnumberofiterationspermittedforCGorGMRES.Thedefaultvalueis1000.tolerance;SPMamp;afloatingpointnumberspecifyingtheterminationcriterionforCGorGMRES.Thedefaultvalueis1.0E-10.pilutFillin;SPMamp;anintegerspecifyingthemaximumnumberofnonzeroskeptintheformationofincompleteLandU.Ifthisisnotcalled,avaluewillbeselectedbasedonthesparsityofthematrix.pilutDropTol;SPMamp;afloatingpointnumberspecifyingthethresholdtodropsmallentriesinLandU.Thedefaultvalueis0.0.euclidNlevels;SPMamp;anon-negativeintegerspecifyingthedesiredsparsityoftheincompletefactors.Thedefaultvalueis0.euclidThreshold;SPMamp;afloatingpointnumberspecifyingthethresholdusedtosparsifytheincompletefactors.Thedefaultvalueis0.0.superluOrdering;SPMamp;codenatural(default)orcodemmd(minimumdegreeordering).ThisorderingisusedtominimizethenumberofnonzerosgeneratedintheLUdecomposition.Thedefaultisnaturalordering.superluScale;SPMamp;codey(yes;performrowandcolumnscalingsbeforedecomposition)orcoden(no;default).amgCoarsenType;SPMamp;codefalgout,coderuge,orcodedefault(CLJP)coarseningforBoomerAMG.amgNumSweeps;SPMamp;anintegerspecifyingthenumberofpre-andpost-smoothingateachlevelofBoomerAMG.Thedefaultisonepre-andonepost-smoothings.amgRelaxType;SPMamp;codejacobi(DampedJacobi),codegs-slow(sequentialGauss-Seidel),codegs-fast(Gauss-Seideloninteriornodes),codehybrid,orcodedirect.Thedefaultiscodehybrid.amgRelaxWeight;SPMamp;afloatingpointnumberbetween0and1specifyingthedampingfactorforBoomerAMG'sdampedJacobismoother.Thedefaultvalueis0.5.amgStrongThreshold;SPMamp;afloatingpointnumberbetween0and1specifyingthethresholdusedtodeterminestrongcouplinginBoomerAMG'scoasening.Thedefaultvalueis0.25.parasailsThreshold;SPMamp;afloatingpointnumberbetween0and1specifyingthethresholdusedtoprunesmallentriesinsettingupthesparseapproximateinverse.Thedefaultvalueis0.0.parasailsNlevels;SPMamp;anintegerlargerthan0specifyingthedesiredsparsityoftheapproximateinverse.Thedefaultvalueis1.parasailsFilter;SPMamp;afloatingpointnumberbetween0and1definingthethresholdusedtoprunesmallentriesinA.Thedefaultis0.0.parasailsLoadbal;SPMamp;afloatingpointnumberbetween0and1specifyinghowloadbalancinghastobedone.Thedefaultis0.0.parasailsSymmetric;SPMamp;setParaSailstotakeAassymmetric.parasailsUnSymmetric;SPMamp;setParaSailstotakeAasnonsymmetric(default).parasailsReuse;SPMamp;setParaSailstoreusethesparsitypatternofA.hlinetabularlabeltable-fei-param{table}/;
$cached_env_img{$key} = q| <IMG WIDTH=758 HEIGHT=1111 ALIGN=BOTTOM  SRC="img13.gif"  > |; 
$key = q/{_inline}$theta${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=6 HEIGHT=13 ALIGN=BOTTOM  SRC="img21.gif"  > |; 
$key = q/{tabular}ll0;SPMamp;CLJP-coarsening1;SPMamp;Ruge-Stuebencoarseningwithoutboundarytreatment3;SPMamp;Ruge-Stuebencoarseningwitha3rd'second'passontheboundaries6;SPMamp;Falgoutcoarsening(default){tabular}/;
$cached_env_img{$key} = q| <IMG WIDTH=573 HEIGHT=85 ALIGN=BOTTOM  SRC="img22.gif"  > |; 
$key = q/{tabular}|c|l|hlinevalue;SPMamp;meaninghline0;SPMamp;nonsymmetricandorindefiniteproblem,andnonsymmetricpreconditioner1;SPMamp;SPDproblem,andSPD(factored)preconditioner2;SPMamp;nonsymmetric,definiteproblem,andSPD(factored)preconditionerhline{tabular}/;
$cached_env_img{$key} = q| <IMG WIDTH=683 HEIGHT=92 ALIGN=BOTTOM  SRC="img31.gif"  > |; 
$key = q/{_inline}$-ttthresh${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=71 HEIGHT=20 ALIGN=MIDDLE  SRC="img34.gif"  > |; 
$key = q/{_inline}$-ttfilter${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=72 HEIGHT=22 ALIGN=MIDDLE  SRC="img37.gif"  > |; 
$key = q/{_inline}$tildeA^m${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=24 HEIGHT=16 ALIGN=BOTTOM  SRC="img29.gif"  > |; 
$key = q/{_inline}$S_0${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=16 HEIGHT=25 ALIGN=MIDDLE  SRC="img5.gif"  > |; 
$key = q/{table}centertabular|l|l|hlineCparameter;SPMamp;Fortranargumenthlinehlinecodeinti;SPMamp;codeintegericodedoubled;SPMamp;codedoubleprecisiondcodeint*array;SPMamp;codeintegerarray(*)codedouble*array;SPMamp;codedoubleprecisionarray(*)codechar*string;SPMamp;codecharacterstring(*)codeHYPRE_Typeobject;SPMamp;codeinteger*8objectcodeHYPRE_Type*object;SPMamp;codeinteger*8objecthlinetabularlabeltable-fortran-interface-types{table}/;
$cached_env_img{$key} = q| <IMG WIDTH=451 HEIGHT=187 ALIGN=BOTTOM  SRC="img42.gif"  > |; 
$key = q/{_inline}$S_3${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=16 HEIGHT=25 ALIGN=MIDDLE  SRC="img6.gif"  > |; 
$key = q/{figure}[t]centeringincludegraphics[width=4in]fv_grid.epslabelfig-fv-grid{figure}/;
$cached_env_img{$key} = q| <IMG WIDTH=480 HEIGHT=216 ALIGN=BOTTOM  SRC="img2.gif"  > |; 
$key = q/{_inline}$0leitthreshle1${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=111 HEIGHT=27 ALIGN=MIDDLE  SRC="img25.gif"  > |; 
$key = q/{_inline}$itthresh=0.1${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=92 HEIGHT=13 ALIGN=BOTTOM  SRC="img27.gif"  > |; 
$key = q/{tabular}ll0;SPMamp;weightedJacobi1;SPMamp;sequentialGauss-Seidel(veryslow!)3;SPMamp;Gauss-SeidelJacobihybridmethod(default)6;SPMamp;symmetricGauss-SeidelJacobihybridmethod9;SPMamp;Gaussianelimination(onlyforthecoarsestlevel(k=3),notrecommed;SPMamp;ifthesystemonthecoarsestlevelislarge){tabular}/;
$cached_env_img{$key} = q| <IMG WIDTH=616 HEIGHT=131 ALIGN=BOTTOM  SRC="img23.gif"  > |; 
$key = q/{table}[h]centertabular|l||c|c|c|c|hline;SPMamp;multicolumn4|c|SystemInterfacesmulticolumn1|c||Solvers;SPMamp;Struct;SPMamp;SStruct;SPMamp;FEI;SPMamp;IJhlinehlineJacobi;SPMamp;X;SPMamp;;SPMamp;;SPMamp;SMG;SPMamp;X;SPMamp;;SPMamp;;SPMamp;PFMG;SPMamp;X;SPMamp;;SPMamp;;SPMamp;BoomerAMG;SPMamp;;SPMamp;X;SPMamp;X;SPMamp;XParaSails;SPMamp;;SPMamp;X;SPMamp;X;SPMamp;XEuclid;SPMamp;;SPMamp;X;SPMamp;X;SPMamp;XPILUT;SPMamp;;SPMamp;X;SPMamp;X;SPMamp;XPCG;SPMamp;X;SPMamp;X;SPMamp;X;SPMamp;XGMRES;SPMamp;X;SPMamp;X;SPMamp;X;SPMamp;Xhlinetabularlabeltable-solver-availability{table}/;
$cached_env_img{$key} = q| <IMG WIDTH=366 HEIGHT=254 ALIGN=BOTTOM  SRC="img16.gif"  > |; 
$key = q/{_inline}$tildeA${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=12 HEIGHT=16 ALIGN=BOTTOM  SRC="img30.gif"  > |; 
$key = q/{_inline}$(A+A^T)2${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=90 HEIGHT=31 ALIGN=MIDDLE  SRC="img39.gif"  > |; 
$key = q/{_inline}$ttthresh;SPMlt;0${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=88 HEIGHT=25 ALIGN=MIDDLE  SRC="img33.gif"  > |; 
$key = q/{tabular}|c|c|c|c|c|l|hlineparameter;SPMamp;type;SPMamp;range;SPMamp;sug.values;SPMamp;default;SPMamp;meaninghlinettnlevel;SPMamp;integer;SPMamp;_inline$ttnlevelge0$_inline;SPMamp;0,1,2;SPMamp;1;SPMamp;_inline$m=ttnlevel+1$_inlinehlinettthresh;SPMamp;real;SPMamp;_inline$ttthreshge0$_inline;SPMamp;0,0.1,0.01;SPMamp;0.1;SPMamp;emthresh_inline$=$_inlinettthresh;SPMamp;;SPMamp;_inline$ttthresh;SPMlt;0$_inline;SPMamp;-0.75,-0.90;SPMamp;;SPMamp;emthreshselectedautomaticallyhlinettfilter;SPMamp;real;SPMamp;_inline$ttfilterge0$_inline;SPMamp;0,0.05,0.001;SPMamp;0.05;SPMamp;filtervalue_inline$=$_inlinettfilter;SPMamp;;SPMamp;_inline$ttfilter;SPMlt;0$_inline;SPMamp;-0.90;SPMamp;;SPMamp;filtervalueselectedautomaticallyhline{tabular}/;
$cached_env_img{$key} = q| <IMG WIDTH=773 HEIGHT=139 ALIGN=BOTTOM  SRC="img32.gif"  > |; 
$key = q/{_inline}$ttfilter;SPMlt;0${_inline}/;
$cached_env_img{$key} = q| <IMG WIDTH=88 HEIGHT=25 ALIGN=MIDDLE  SRC="img36.gif"  > |; 

1;

