########################################################################
# hypre examples documentation
########################################################################

EXAMPLES_DIR = ..

all:
	@./build_doc.sh $(EXAMPLES_DIR)

clean:
	rm -f *.html

distclean: clean
	rm -f *~
	rm -rf ../*.html ../README_files
