########################################################################
# hypre examples documentation
########################################################################

EXAMPLES_DIR = ..

all:
	@./build_doc.sh $(EXAMPLES_DIR)

clean:
	rm -f *.html

veryclean distclean: clean
	rm -f *~
