#######################################################################
#
#	Makefile for cleaning up libs.
#
#######################################################################

include $(FEI_ROOT)/make.options

clean:
	@touch erase.this
	rm -f */libfei_base*.a erase.*

