#BHEADER***********************************************************************
# (c) 1997   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision$
#EHEADER***********************************************************************

CC = cc
F77 = f77

CFLAGS = -O -DHYPRE_TIMING -DHYPRE_SEQUENTIAL

FFLAGS = -O

MEMORY_EXTRA_FILES =\
 mpistubs.c

include Makefile.generic

