#!/bin/sh
#BHEADER***********************************************************************
# (c) 1999   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision$
#EHEADER***********************************************************************

while [ $# -ge 1 ]; do
    echo ""; echo "/* $1 */"
    perl -e 'while ($line = <>) {if ($line =~ /#else|#elif/) {0 while(<> !~ /#endif/);} elsif ($line !~ /#if|#endif/) {print("$line");}}' $1 | mkproto -p | grep -v " main[ (]"
    shift
done
