#!/bin/sh

if [ $# -lt 2 ] ; then
  echo "sample usage: "
  echo "  build seq  solaris g" 
  echo "  build mpi  solaris g" 
  echo "  build petsc solaris g" 
  echo "  use: "
  echo "     build seq  solaris g x"
  echo "  to rebuild all."
  echo
  exit 1
fi

cd $PCPACK_DIR/src

if [ $# = 4 ] ; then
  rm *.o
  echo "#ifndef PCPACK_HOME_DH" > ../include/home_dh.h
  echo "#define PCPACK_HOME_DH" >> ../include/home_dh.h
  echo "#define MASTER_OPTIONS_LIST \"$PCPACK_DIR/include/options_database\" " >> ../include/home_dh.h
  echo "#endif" >> ../include/home_dh.h
  echo "make WHICH_MAKE=$1 PCPACK_PHOO=$2 BOPT=$3 pall"
  make WHICH_MAKE=$1 PCPACK_PHOO=$2 BOPT=$3 pall
else
  echo "make WHICH_MAKE=$1 PCPACK_PHOO=$2 BOPT=$3 pall"
  make WHICH_MAKE=$1 PCPACK_PHOO=$2 BOPT=$3 pall
fi
