#!/bin/bash
# Copyright (c) 1998 Lawrence Livermore National Security, LLC and other
# HYPRE Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

while [ $# -ge 1 ]; do
    echo ""; echo "/* $1 */"
    perl -e 'while ($line = <>) {if ($line =~ /#else|#elif/) {0 while(<> !~ /#endif/);} elsif ($line !~ /#if|#endif/) {print("$line");}}' $1 | mkproto -p | grep -v " main[ (]"
    shift
done
