#!/bin/sh
#BHEADER***********************************************************************
# (c) 1999   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision: 2.0 $
#EHEADER***********************************************************************

mkproto $* \
 | awk '(NR > 6) && ($1 !~ /#undef/)' \
 | sed -e 's/ P((/( /g; s/);/;/g'

