#define SIDL_opaque__array_create2dCol_m ary_create2dCol6fla10yc0bqh17_m
#define sidl_opaque__array_create2dcol_m ary_create2dcol6fla10yc0bqh17_m
#define SIDL_OPAQUE__ARRAY_CREATE2DCOL_M ARY_CREATE2DCOL6FLA10YC0BQH17_M

#define SIDL_opaque__array_create2dRow_m ary_create2dRowz2l3ocbhjxuzdf_m
#define sidl_opaque__array_create2drow_m ary_create2drowz2l3ocbhjxuzdf_m
#define SIDL_OPAQUE__ARRAY_CREATE2DROW_M ARY_CREATE2DROWZ2L3OCBHJXUZDF_M

#define SIDL_opaque__array_isColumnOrder_m ary_isColumnOrderf13nr7s0sfv2_m
#define sidl_opaque__array_iscolumnorder_m ary_iscolumnorderf13nr7s0sfv2_m
#define SIDL_OPAQUE__ARRAY_ISCOLUMNORDER_M ARY_ISCOLUMNORDERF13NR7S0SFV2_M

