#define SIDL_string__array_create2dCol_m ary_create2dColiv96_oajh8f6w4_m
#define sidl_string__array_create2dcol_m ary_create2dcoliv96_oajh8f6w4_m
#define SIDL_STRING__ARRAY_CREATE2DCOL_M ARY_CREATE2DCOLIV96_OAJH8F6W4_M

#define SIDL_string__array_create2dRow_m ary_create2dRowp7z_7l8db6slve_m
#define sidl_string__array_create2drow_m ary_create2drowp7z_7l8db6slve_m
#define SIDL_STRING__ARRAY_CREATE2DROW_M ARY_CREATE2DROWP7Z_7L8DB6SLVE_M

#define SIDL_string__array_isColumnOrder_m ary_isColumnOrdert_rdahsudbbw_m
#define sidl_string__array_iscolumnorder_m ary_iscolumnordert_rdahsudbbw_m
#define SIDL_STRING__ARRAY_ISCOLUMNORDER_M ARY_ISCOLUMNORDERT_RDAHSUDBBW_M

