#define SIDL_fcomplex__array_create2dCol_m ary_create2dColnu_a7gr0xha137_m
#define sidl_fcomplex__array_create2dcol_m ary_create2dcolnu_a7gr0xha137_m
#define SIDL_FCOMPLEX__ARRAY_CREATE2DCOL_M ARY_CREATE2DCOLNU_A7GR0XHA137_M

#define SIDL_fcomplex__array_create2dRow_m ary_create2dRow0w84vbbl90fb5f_m
#define sidl_fcomplex__array_create2drow_m ary_create2drow0w84vbbl90fb5f_m
#define SIDL_FCOMPLEX__ARRAY_CREATE2DROW_M ARY_CREATE2DROW0W84VBBL90FB5F_M

#define SIDL_fcomplex__array_createCol_m fc_ary_createColrntwhb8rhunnx_m
#define sidl_fcomplex__array_createcol_m fc_ary_createcolrntwhb8rhunnx_m
#define SIDL_FCOMPLEX__ARRAY_CREATECOL_M FC_ARY_CREATECOLRNTWHB8RHUNNX_M

#define SIDL_fcomplex__array_createRow_m fc_ary_createRowumpp98gavsfml_m
#define sidl_fcomplex__array_createrow_m fc_ary_createrowumpp98gavsfml_m
#define SIDL_FCOMPLEX__ARRAY_CREATEROW_M FC_ARY_CREATEROWUMPP98GAVSFML_M

#define SIDL_fcomplex__array_deleteRef_m fc_ary_deleteRefckwappc1nseei_m
#define sidl_fcomplex__array_deleteref_m fc_ary_deleterefckwappc1nseei_m
#define SIDL_FCOMPLEX__ARRAY_DELETEREF_M FC_ARY_DELETEREFCKWAPPC1NSEEI_M

#define SIDL_fcomplex__array_isColumnOrder_m ary_isColumnOrdero9g8sjcool59_m
#define sidl_fcomplex__array_iscolumnorder_m ary_iscolumnordero9g8sjcool59_m
#define SIDL_FCOMPLEX__ARRAY_ISCOLUMNORDER_M ARY_ISCOLUMNORDERO9G8SJCOOL59_M

#define SIDL_fcomplex__array_isRowOrder_m f_ary_isRowOrdera41hjkeeazj7p_m
#define sidl_fcomplex__array_isroworder_m f_ary_isrowordera41hjkeeazj7p_m
#define SIDL_FCOMPLEX__ARRAY_ISROWORDER_M F_ARY_ISROWORDERA41HJKEEAZJ7P_M

#define SIDL_fcomplex__array_smartCopy_m fc_ary_smartCopyw6fiaq4cwwi3y_m
#define sidl_fcomplex__array_smartcopy_m fc_ary_smartcopyw6fiaq4cwwi3y_m
#define SIDL_FCOMPLEX__ARRAY_SMARTCOPY_M FC_ARY_SMARTCOPYW6FIAQ4CWWI3Y_M

