#!/bin/sh
# Copyright 1998-2019 Lawrence Livermore National Security, LLC and other
# HYPRE Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

# Apply code formatting
( cd $(git rev-parse --show-toplevel)/src; ./config/astyle-apply.sh . )

