#!/bin/sh
#BHEADER**********************************************************************
# Copyright (c) 2006   The Regents of the University of California.
# Produced at the Lawrence Livermore National Laboratory.
# Written by the HYPRE team <hypre-users@llnl.gov>, UCRL-CODE-222953.
# All rights reserved.
#
# This file is part of HYPRE (see http://www.llnl.gov/CASC/hypre/).
# Please see the COPYRIGHT_and_LICENSE file for the copyright notice, 
# disclaimer and the GNU Lesser General Public License.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License (as published by the Free
# Software Foundation) version 2.1 dated February 1999.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the IMPLIED WARRANTY OF MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the terms and conditions of the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
# $Revision$
#EHEADER**********************************************************************


#===========================================================================
# This script builds all of the code in the AMG directory structure
#===========================================================================

AMG_SRC="."

. $AMG_SRC/config/build_generic

#=======================================================
# Untar `cvode'
#=======================================================
 
if [ ! -d "$AMG_SRC/cvode" ]; then
  echo "Untarring cvode ..."
  (cd $AMG_SRC; gtar xzf cvode.tar.Z; mv CVODE cvode)
  (cd $AMG_SRC; cp cvode.build cvode/build)
fi

#=============================================================================
# Build
#=============================================================================

DIRS="tools amgdriver"

for i in $DIRS
do
   (cd $AMG_SRC/$i; ./build $AMG_BUILD_ARGS)
done

