#!/bin/sh
#BHEADER**********************************************************************
# Copyright (c) 2007, Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory.
# Written by the HYPRE team. UCRL-CODE-222953.
# All rights reserved.
#
# This file is part of HYPRE (see http://www.llnl.gov/CASC/hypre/).
# Please see the COPYRIGHT_and_LICENSE file for the copyright notice, 
# disclaimer, contact information and the GNU Lesser General Public License.
#
# HYPRE is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License (as published by the Free Software 
# Foundation) version 2.1 dated February 1999.
#
# HYPRE is distributed in the hope that it will be useful, but WITHOUT ANY 
# WARRANTY; without even the IMPLIED WARRANTY OF MERCHANTABILITY or FITNESS 
# FOR A PARTICULAR PURPOSE.  See the terms and conditions of the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
# $Revision$
#EHEADER**********************************************************************





#===========================================================================
# This script creates a tar file of the AMG library distribution
#===========================================================================

TOP_DIR="$AMG_SRC/tmp"

mkdir -p $TOP_DIR/amg
mkdir -p $TOP_DIR/amg/src
mkdir -p $TOP_DIR/amg/config
mkdir -p $TOP_DIR/amg/examples
mkdir -p $TOP_DIR/amg/docs

(cd $AMG_SRC/amg;        cp `cat rcs_files` $TOP_DIR/amg/src)
(cd $AMG_SRC/config;     cp `cat rcs_files` $TOP_DIR/amg/config)
(cd $AMG_SRC/amg_fdrive; cp `cat rcs_files` $TOP_DIR/amg/examples)
(cd $AMG_SRC/docs;       cp `cat rcs_files` $TOP_DIR/amg/docs)
(cd $AMG_SRC;            cp amg.readme      $TOP_DIR)

(cd $TOP_DIR; gtar czf $AMG_SRC/amg.tgz amg amg.readme)

rm -fr $TOP_DIR
