#!/bin/csh
# makes links to AMG data files

set AMGDAT = $1

rm -f AMG.in.ysmp
ln -s -v $AMGDAT.in.ysmp AMG.in.ysmp

rm -f AMG.in.rhs
ln -s -v $AMGDAT.in.rhs AMG.in.rhs

rm -f AMG.in.initu
ln -s -v $AMGDAT.in.initu AMG.in.initu

rm -f AMG.in.prob
ln -s -v $AMGDAT.in.prob AMG.in.prob
