#!/bin/sh
#BHEADER**********************************************************************
# Copyright (c) 2008,  Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory.
# This file is part of HYPRE.  See file COPYRIGHT for details.
#
# HYPRE is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License (as published by the Free
# Software Foundation) version 2.1 dated February 1999.
#
# $Revision$
#EHEADER**********************************************************************








################################################################################
#
# Shell script that uses `mkproto' to create a prototype header files.
#
################################################################################

################################################################################
# Echo the `amg.h' prototypes to stdout
################################################################################

FILES="
 amg.c
 amg_params.c
 amg_cycle.c
 amg_relax.c
 amg_setup.c
 amg_solve.c
 vector.c
 matrix.c
"

mkproto -s $FILES

################################################################################
# Create the `protos.h' file
################################################################################

PROTOS="protos.h"

cat > $PROTOS <<@

#ifndef HYPRE_PROTOS_HEADER
#define HYPRE_PROTOS_HEADER

@

mkproto -s `echo * | \
awk '
   BEGIN {STR = " "}
   {
      for (i = 1; i <= NF; i++) {
         if (($i  ~ /[^\ ]*\.c/) && \
             ($i !~ /f90.*/)        )
            STR = STR $i " "
      }
   }
   END {print STR}
'` >> $PROTOS


cat >> $PROTOS <<@

#endif

@

