#!/bin/bash
# Copyright (c) 1998 Lawrence Livermore National Security, LLC and other
# HYPRE Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

# Generate multiprecision code
#
# The script takes an external header file, an internal header file, and an
# output file prefix, then generates various C files and header files.
#
# The generated files begin with the prefix name and contain code corresponding
# to the functions listed in mup.fixed, mup.functions, and mup.methods (methods
# are not fully implemented yet - see NOTE below).
#
# Usage:   <this-script> <external-header> <internal-header> <prefix>
# Example: <this-script> HYPRE_krylov.h _hypre_krylov.h mup

scriptdir=`dirname $0`

EXTH=$1
INTH=$2
OUTP=$3

#### NOTE: Add mup.methods to this later.
####
#### It should be easy to just add it to the loops below, but some up-front
#### preprocessing will be necessary to move existing implementation code out of
#### the way temporarily to prevent overwriting existing code.  Developers will
#### then need to do a manual merge.  The header files can be generated fully
#### automatically as below.

############################################################################
# Define gpu tag - set to an empty string if there are no gpu list files
#
# Note that the following line will always generate an empty-string value for c,
# but it will only generate another value for c when $gpu is non-empty
#
#     for c in "" $gpu    --> c=""               when gpu=""
#                         --> c="", c="$gpu"     when gpu="non-empty-string"
#
# This is useful below for executing the same lines of code for the normal case
# and the gpu case (and potential future cases).
#
############################################################################

gpu=""
if [ -f mup.fixed.gpu ]
then
   gpu=".gpu"
fi

############################################################################
# Make sure the function list files are sorted (list capital letters first)
############################################################################

for c in "" $gpu
do
   for i in fixed functions methods
   do
      tag=${i}${c}
      (export LC_COLLATE=C; sort mup.${tag} | uniq) > mup.${tag}.tmp
      mv mup.${tag}.tmp mup.${tag}
   done
done

############################################################################
# Generate def/undef header files
############################################################################

extp=${EXTH%.*}  # extract the prefix from the external header
intp=${INTH%.*}  # extract the prefix from the internal header

# strip off leading 'HYPRE_' or '_hypre_' and convert to uppercase
extname=`echo $extp | sed -e 's/HYPRE_//g' -e 's/_hypre_//g' | awk '{print toupper($0)}'`
intname=`echo $intp | sed -e 's/HYPRE_//g' -e 's/_hypre_//g' | awk '{print toupper($0)}'`

#============================================================
# Create def header file
#============================================================

MUP_HEADER=${intp}_mup_def.h

cat > $MUP_HEADER <<@

/*** DO NOT EDIT THIS FILE DIRECTLY (use $0 to generate) ***/

@

# Generate copyright header
$scriptdir/write_header.sh >> $MUP_HEADER

cat >> $MUP_HEADER <<@
/* Header file for transforming multiprecision functions names */

#ifndef hypre_${intname}_MUP_DEF_HEADER
#define hypre_${intname}_MUP_DEF_HEADER

#include "_hypre_mup_def.h"

@

cat>> $MUP_HEADER <<@
$(
   for c in "" $gpu
   do
      for i in functions methods
      do
         tag=${i}${c}
         cat mup.${tag} | while read -r func_name
         do
            echo "#define $func_name HYPRE_MULTIPRECISION_FUNC ( $func_name )"
         done
      done
      for i in fixed
      do
         tag=${i}${c}
         cat mup.${tag} | while read -r func_name
         do
            echo "#define $func_name HYPRE_FIXEDPRECISION_FUNC ( $func_name )"
         done
      done
   done
)

#endif
@

#============================================================
# Exit if we only need the def header file
#============================================================

if [ "${OUTP}" = "onlydef" ]
then
   exit
fi

#============================================================
# Create undef header file
#============================================================

MUP_HEADER=${intp}_mup_undef.h

cat > $MUP_HEADER <<@

/*** DO NOT EDIT THIS FILE DIRECTLY (use $0 to generate) ***/

@

# Generate copyright header
$scriptdir/write_header.sh >> $MUP_HEADER

cat >> $MUP_HEADER <<@
/* Header file for transforming multiprecision functions names */

#undef hypre_${intname}_MUP_DEF_HEADER

@

cat>> $MUP_HEADER <<@
$(
   for c in "" $gpu
   do
      for i in functions methods fixed
      do
         tag=${i}${c}
         cat mup.${tag} | while read -r func_name
         do
            echo "#undef $func_name"
         done
      done
   done
)
@

############################################################################
# Create temporary files and initial code
############################################################################

# Create prototype information files
for c in "" $gpu
do
   for i in fixed functions methods
   do
      tag=${i}${c}
      $scriptdir/gen_proto_info.sh mup.${tag} ${EXTH} > ${OUTP}.${tag}.ext.proto
      $scriptdir/gen_proto_info.sh mup.${tag} ${INTH} > ${OUTP}.${tag}.int.proto
   done
   cat ${OUTP}.functions${c}.ext.proto ${OUTP}.methods${c}.ext.proto > ${OUTP}.pre${c}.ext.proto
   cat ${OUTP}.functions${c}.int.proto ${OUTP}.methods${c}.int.proto > ${OUTP}.pre${c}.int.proto
done

# Create C implementation files and header files
for c in "" $gpu
do
   for i in fixed functions pre
   do
      tag=${i}${c}
      $scriptdir/gen_code_awk.sh ${OUTP}.${tag}.ext.proto ${OUTP}_${tag}_ext ${i}
      $scriptdir/gen_code_awk.sh ${OUTP}.${tag}.int.proto ${OUTP}_${tag}_int ${i}
   done
done

############################################################################
# Finalize code
############################################################################

#============================================================
# Create implementation files
#============================================================

for i in fixed functions pre
do

FOUT=${OUTP}_${i}.c

cat > $FOUT <<@

/*** DO NOT EDIT THIS FILE DIRECTLY (use $0 to generate) ***/

#include "$INTH"

#ifdef HYPRE_MIXED_PRECISION

@

$scriptdir/write_header.sh >> $FOUT
cat ${OUTP}_${i}_ext.c ${OUTP}_${i}_int.c >> $FOUT
if [ -n "$gpu" ]
then
   echo "#if defined(HYPRE_USING_GPU)"                   >> $FOUT
   cat ${OUTP}_${i}${gpu}_ext.c ${OUTP}_${i}${gpu}_int.c >> $FOUT
   echo "#endif"                                         >> $FOUT
fi

cat >> $FOUT <<@

#endif

@

done

#============================================================
# Create external header file
#============================================================

FOUT=${extp}_mup.h

cat > $FOUT <<@

/*** DO NOT EDIT THIS FILE DIRECTLY (use $0 to generate) ***/

#ifndef HYPRE_${extname}_MUP_HEADER
#define HYPRE_${extname}_MUP_HEADER

#ifdef __cplusplus
extern "C" {
#endif

#if defined (HYPRE_MIXED_PRECISION)
@

for i in fixed functions pre
do
   # Note that the following 'cat' and 'write_header' lines are not needed - remove later
   cat >> $FOUT <<@

/*** DO NOT EDIT THIS FILE DIRECTLY (use $0 to generate) ***/

@
   $scriptdir/write_header.sh  >> $FOUT
   cat ${OUTP}_${i}_ext.h      >> $FOUT
   if [ -n "$gpu" ]
   then
      echo "#if defined(HYPRE_USING_GPU)"   >> $FOUT
      cat ${OUTP}_${i}${gpu}_ext.h          >> $FOUT
      echo "#endif"                         >> $FOUT
   fi
done

cat >> $FOUT <<@

#endif

#ifdef __cplusplus
}
#endif

#endif

@

#============================================================
# Create internal header file
#============================================================

FOUT=${intp}_mup.h

cat > $FOUT <<@

/*** DO NOT EDIT THIS FILE DIRECTLY (use $0 to generate) ***/

#ifndef hypre_${intname}_MUP_HEADER
#define hypre_${intname}_MUP_HEADER

#ifdef __cplusplus
extern "C" {
#endif

#if defined (HYPRE_MIXED_PRECISION)
@

for i in fixed functions pre
do
   # Note that the following 'cat' and 'write_header' lines are not needed - remove later
   cat >> $FOUT <<@

/*** DO NOT EDIT THIS FILE DIRECTLY (use $0 to generate) ***/

@
   $scriptdir/write_header.sh  >> $FOUT
   cat ${OUTP}_${i}_int.h      >> $FOUT
   if [ -n "$gpu" ]
   then
      echo "#if defined(HYPRE_USING_GPU)"   >> $FOUT
      cat ${OUTP}_${i}${gpu}_int.h          >> $FOUT
      echo "#endif"                         >> $FOUT
   fi
done

cat >> $FOUT <<@

#endif

#ifdef __cplusplus
}
#endif

#endif

@

############################################################################
# Remove temporary files
############################################################################

for c in "" $gpu
do
   for i in fixed functions methods pre
   do
      tag=${i}${c}
      rm -f ${OUTP}.${tag}.ext.proto
      rm -f ${OUTP}.${tag}.int.proto
      rm -f ${OUTP}_${tag}_ext.[ch]
      rm -f ${OUTP}_${tag}_int.[ch]
   done
done

