#BHEADER**********************************************************************
# Copyright (c) 2006   The Regents of the University of California.
# Produced at the Lawrence Livermore National Laboratory.
# Written by the HYPRE team. UCRL-CODE-222953.
# All rights reserved.
#
# This file is part of HYPRE (see http://www.llnl.gov/CASC/hypre/).
# Please see the COPYRIGHT_and_LICENSE file for the copyright notice, 
# disclaimer, contact information and the GNU Lesser General Public License.
#
# HYPRE is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License (as published by the Free Software 
# Foundation) version 2.1 dated February 1999.
#
# HYPRE is distributed in the hope that it will be useful, but WITHOUT ANY 
# WARRANTY; without even the IMPLIED WARRANTY OF MERCHANTABILITY or FITNESS 
# FOR A PARTICULAR PURPOSE.  See the terms and conditions of the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
# $Revision: 1.26 $
#EHEADER**********************************************************************




###############################################################################
##  All configurable variables are defined in the file named Makefile.config.in
##  When Autoconf is run, it will create a file named Makefile.config which
##  will have all of the configurable variables replaced with their values.
###############################################################################




srcdir = .
top_srcdir = ..
prefix = /home/falgout/tmprelease/hypre-1.14.0b
exec_prefix = ${prefix}



HYPRE_SRC_TOP_DIR = /home/falgout/tmprelease/hypre-1.14.0b/src/linear_solvers
HYPRE_BUILD_DIR = /home/falgout/tmprelease/hypre-1.14.0b/src/linear_solvers/hypre
HYPRE_LINK_DIR = /home/falgout/tmprelease/hypre-1.14.0b/src/linear_solvers/hypre

HYPRE_RELEASE_VERSION = 1.14.0b
HYPRE_RELEASE_DATE = 2006/11/30
HYPRE_RELEASE_TIME = 14:48:32
HYPRE_RELEASE_DATETIME = 2006/11/30 14:48:32

HYPRE_INSTALL_DIR = /home/falgout/tmprelease/hypre-1.14.0b
HYPRE_LIB_INSTALL = ${exec_prefix}/lib
HYPRE_INC_INSTALL = ${prefix}/include

HYPRE_LIB_SUFFIX = .a


.SUFFIXES:
.SUFFIXES: .o .f .c .C .cxx .cc

.f.o:
	$(F77) $(FFLAGS) $(FDEFS) -c $< 
.c.o:
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< 
.C.o:
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $<
.cxx.o:
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $<
.cc.o:
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $<


F77       = mpif77
FFLAGS    = -O  $(F77_COMPILE_FLAGS)
FDEFS     = -DHAVE_CONFIG_H

CC        = mpicc
CFLAGS    = -O2 $(C_COMPILE_FLAGS)

CXX       = mpiCC
CXXFLAGS  = -O2 $(CXX_COMPILE_FLAGS)

CPPFLAGS  = -DHAVE_CONFIG_H

LINK_F77  = mpif77
LINK_CC   = mpicc
LINK_CXX  = mpiCC

BUILD_F77_SHARED = 
BUILD_CC_SHARED  = 
BUILD_CXX_SHARED = 

BUILD_PYTHON = 0
PYTHON = 

AR	  = ar -rcu
RANLIB    = ranlib

LDFLAGS   = -L/usr/lib/gcc-lib/i386-redhat-linux/3.2.3 -L/usr/lib -L/usr/local/lib -L/usr/apps/lib -L/lib 
LDLIBS    = 
LDLIBDIRS = 

INCLUDES = 
LIBDIRS = 
LIBS = -lg2c    -lm -lstdc++
FLIBS =  -L/usr/apps/mpich/1.2.5.2-gnu/lib -L/usr/lib/gcc-lib/i386-redhat-linux/3.2.3 -L/usr/lib/gcc-lib/i386-redhat-linux/3.2.3/../../.. -lmpich -lfrtbegin -lg2c -lm -lgcc_s

##################################################################
##  BABEL Directories
##################################################################
HYPRE_BABEL_DIRS = 

##################################################################
##  Examples Directory
##################################################################
HYPRE_EXAMPLE_DIRS = 

##################################################################
##  LAPACK Library Flags 
##################################################################
HYPRE_LAPACK_SRC_DIR = /home/falgout/tmprelease/hypre-1.14.0b/src/linear_solvers/lapack
LAPACKLIBS = -lHYPRE_utilities
LAPACKLIBDIRS = -L/home/falgout/tmprelease/hypre-1.14.0b/src/linear_solvers/hypre/lib

##################################################################
##  BLAS Library Flags 
##################################################################
HYPRE_BLAS_SRC_DIR = /home/falgout/tmprelease/hypre-1.14.0b/src/linear_solvers/blas
BLASLIBS = -lHYPRE_utilities
BLASLIBDIRS = -L/home/falgout/tmprelease/hypre-1.14.0b/src/linear_solvers/hypre/lib

##################################################################
##  MPI options
##################################################################
MPIINCLUDE = 
MPILIBDIRS = 
MPILIBS =  
MPIFLAGS = 

##################################################################
##  FEI options
##################################################################
FEIINCLUDE = 
FEILIBS = 
FEILIBDIRS = 
HYPRE_FEI_SRC_DIR = /home/falgout/tmprelease/hypre-1.14.0b/src/linear_solvers/FEI_mv
HYPRE_FEI_BASE_DIR = /home/falgout/tmprelease/hypre-1.14.0b/src/linear_solvers/FEI_mv/fei-base
HYPRE_FEI_SUBDIRS = SuperLU fei-hypre femli
HYPRE_FEI_SUPERLU_FILES = /home/falgout/tmprelease/hypre-1.14.0b/src/linear_solvers/FEI_mv/SuperLU/*.*o
HYPRE_FEI_HYPRE_FILES = /home/falgout/tmprelease/hypre-1.14.0b/src/linear_solvers/FEI_mv/fei-hypre/*.*o
HYPRE_FEI_FEMLI_FILES = /home/falgout/tmprelease/hypre-1.14.0b/src/linear_solvers/FEI_mv/femli/lib/*.*o
