#BHEADER**********************************************************************
# Copyright (c) 2008,  Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory.
# This file is part of HYPRE.  See file COPYRIGHT for details.
#
# HYPRE is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License (as published by the Free
# Software Foundation) version 2.1 dated February 1999.
#
# $Revision: 1.34 $
#EHEADER**********************************************************************


###############################################################################
##  All configurable variables are defined in the file named Makefile.config.in
##  When Autoconf is run, it will create a file named Makefile.config which
##  will have all of the configurable variables replaced with their values.
###############################################################################



srcdir = .
top_srcdir = ..
prefix = /home/falgout/hypre_releases/new_release/hypre-2.8.0b
exec_prefix = ${prefix}



HYPRE_RELEASE_NAME    = hypre
HYPRE_RELEASE_VERSION = 2.8.0b
HYPRE_RELEASE_DATE    = 2011/11/14
HYPRE_RELEASE_TIME    = 00:00:00
HYPRE_RELEASE_BUGS    = hypre-support@llnl.gov

HYPRE_SRC_TOP_DIR = /home/falgout/hypre_releases/new_release/hypre-2.8.0b/src/linear_solvers
HYPRE_BUILD_DIR   = /home/falgout/hypre_releases/new_release/hypre-2.8.0b/src/linear_solvers/hypre

HYPRE_INSTALL_DIR = /home/falgout/hypre_releases/new_release/hypre-2.8.0b
HYPRE_LIB_INSTALL = ${exec_prefix}/lib
HYPRE_INC_INSTALL = ${prefix}/include

HYPRE_LIB_SUFFIX = .a

.SUFFIXES:
.SUFFIXES: .o .f .c .C .cxx .cc

.f.o:
	$(F77) $(FFLAGS) -c $< 
.c.o:
	$(CC) $(CFLAGS) -c $< 
.C.o:
	$(CXX) $(CXXFLAGS) -c $<
.cxx.o:
	$(CXX) $(CXXFLAGS) -c $<
.cc.o:
	$(CXX) $(CXXFLAGS) -c $<

F77       = mpif77
FFLAGS    = -O2  $(F77_COMPILE_FLAGS)

CC        = mpicc
CFLAGS    = -O2 -DHAVE_CONFIG_H $(C_COMPILE_FLAGS)

CXX       = mpicxx
CXXFLAGS  = -O -DHAVE_CONFIG_H $(CXX_COMPILE_FLAGS)

LINK_F77  = mpif77
LINK_CC   = mpicc
LINK_CXX  = mpicxx

BUILD_F77_SHARED    = 
BUILD_CC_SHARED     = 
BUILD_CXX_SHARED    = 
SHARED_COMPILE_FLAG = 
SHARED_BUILD_FLAG   = 
SHARED_SET_SONAME   = 
SHARED_OPTIONS      = 

BUILD_PYTHON = 0
PYTHON       = 

BUILD_JAVA = 0

AR     = ar -rcu
RANLIB = ranlib

LDFLAGS = 
LIBS    =    -lstdc++ -lm
FLIBS   =  -L/home/falgout/codes/mpich2-1.4.1-install/lib -L/usr/lib/gcc/x86_64-redhat-linux/3.4.6 -L/usr/lib/gcc/x86_64-redhat-linux/3.4.6/../../../../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/3.4.6/../../.. -L/lib/../lib64 -L/usr/lib/../lib64 -lmpich -lopa -lmpl -lrt -lpthread -lfrtbegin -lg2c -lm -lgcc_s

##################################################################
##  BABEL Directories
##################################################################
HYPRE_BABEL_DIRS = 

##################################################################
##  Examples Directory
##################################################################
HYPRE_EXAMPLE_DIRS = 

##################################################################
##  LAPACK Library Flags 
##################################################################
HYPRE_LAPACK_SRC_DIR = /home/falgout/hypre_releases/new_release/hypre-2.8.0b/src/linear_solvers/lapack
LAPACKLIBS           = 
LAPACKLIBDIRS        = 

##################################################################
##  BLAS Library Flags 
##################################################################
HYPRE_BLAS_SRC_DIR = /home/falgout/hypre_releases/new_release/hypre-2.8.0b/src/linear_solvers/blas
BLASLIBS           = 
BLASLIBDIRS        = 

##################################################################
##  MPI options
##################################################################
MPIINCLUDE = 
MPILIBDIRS = 
MPILIBS    =  
MPIFLAGS   = 

##################################################################
##  FEI options
##################################################################
HYPRE_FEI_SRC_DIR       = /home/falgout/hypre_releases/new_release/hypre-2.8.0b/src/linear_solvers/FEI_mv
HYPRE_FEI_BASE_DIR      = /home/falgout/hypre_releases/new_release/hypre-2.8.0b/src/linear_solvers/FEI_mv/fei-base
HYPRE_FEI_SUBDIRS       = SuperLU femli fei-hypre
HYPRE_FEI_SUPERLU_FILES = /home/falgout/hypre_releases/new_release/hypre-2.8.0b/src/linear_solvers/FEI_mv/SuperLU/SRC/*.o
HYPRE_FEI_HYPRE_FILES   = /home/falgout/hypre_releases/new_release/hypre-2.8.0b/src/linear_solvers/FEI_mv/fei-hypre/*.o
HYPRE_FEI_FEMLI_FILES   = /home/falgout/hypre_releases/new_release/hypre-2.8.0b/src/linear_solvers/FEI_mv/femli/lib/*.o
