#!/bin/sh
set -x
rm -Rf aclocal.m4 configure autom4te.cache
libtoolize --force --copy
aclocal -I config
autoheader --force --include=config
automake --add-missing --copy --force-missing --foreign
autoconf --include=config
