#!/bin/sh
#set -x
rm -Rf aclocal.m4 configure autom4te.cache
cp /usr/apps/libtool/1.5/share/aclocal/libtool.m4 aclocal.m4
libtoolize --force --copy
aclocal -I config
autoheader --force --include=config
automake --add-missing --copy --force-missing --foreign
autoconf --include=config
