#!/bin/sh
#BHEADER**********************************************************************
# Copyright (c) 2008,  Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory.
# This file is part of HYPRE.  See file COPYRIGHT for details.
#
# HYPRE is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License (as published by the Free
# Software Foundation) version 2.1 dated February 1999.
#
# $Revision: 2.8 $
#EHEADER**********************************************************************







INTERNAL_HEADER=_hypre_IJ_mv.h

#===========================================================================
# Include guards and other includes
#===========================================================================

cat > $INTERNAL_HEADER <<@

#include <HYPRE_config.h>

#ifndef hypre_IJ_HEADER
#define hypre_IJ_HEADER

#include "_hypre_utilities.h"
#include "seq_mv.h"
#include "_hypre_parcsr_mv.h"
#include "HYPRE_IJ_mv.h"

#ifdef __cplusplus
extern "C" {
#endif

@

#===========================================================================
# Structures and prototypes
#===========================================================================

cat aux_parcsr_matrix.h  >> $INTERNAL_HEADER
cat aux_par_vector.h     >> $INTERNAL_HEADER
cat IJ_matrix.h          >> $INTERNAL_HEADER
cat IJ_vector.h          >> $INTERNAL_HEADER

../utilities/protos aux_*.c                   >> $INTERNAL_HEADER
../utilities/protos IJ*.c                     >> $INTERNAL_HEADER
../utilities/protos HYPRE_IJ*.c               >> $INTERNAL_HEADER


#===========================================================================
# Include guards
#===========================================================================

cat >> $INTERNAL_HEADER <<@

#ifdef __cplusplus
}
#endif

#endif

@

