#!/bin/sh
#BHEADER**********************************************************************
# Copyright (c) 2008,  Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory.
# This file is part of HYPRE.  See file COPYRIGHT for details.
#
# HYPRE is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License (as published by the Free
# Software Foundation) version 2.1 dated February 1999.
#
# $Revision: 2.8 $
#EHEADER**********************************************************************





INTERNAL_HEADER=krylov.h

#===========================================================================
# Include guards and other includes
#===========================================================================

cat ../tools/BHEAD_code_template > $INTERNAL_HEADER
cat >> $INTERNAL_HEADER <<@

#include "HYPRE_krylov.h"

#ifndef hypre_KRYLOV_HEADER
#define hypre_KRYLOV_HEADER

#include <stdlib.h>
#include <stdio.h>
#include <math.h>

#include "_hypre_utilities.h"

#define hypre_CTAllocF(type, count, funcs) \
( (type *)(*(funcs->CAlloc))\
((size_t)(count), (size_t)sizeof(type)) )

#define hypre_TFreeF( ptr, funcs ) \
( (*(funcs->Free))((char *)ptr), ptr = NULL )

#ifdef __cplusplus
extern "C" {
#endif

@

#===========================================================================
# Structures and prototypes
#===========================================================================

cat bicgstab.h   >> $INTERNAL_HEADER
cat cgnr.h       >> $INTERNAL_HEADER
cat gmres.h      >> $INTERNAL_HEADER
cat lgmres.h      >> $INTERNAL_HEADER
cat flexgmres.h      >> $INTERNAL_HEADER
cat pcg.h        >> $INTERNAL_HEADER

../utilities/protos bicgstab.c            >> $INTERNAL_HEADER
../utilities/protos cgnr.c                >> $INTERNAL_HEADER
../utilities/protos gmres.c               >> $INTERNAL_HEADER
../utilities/protos flexgmres.c           >> $INTERNAL_HEADER
../utilities/protos lgmres.c               >> $INTERNAL_HEADER
../utilities/protos HYPRE_bicgstab.c      >> $INTERNAL_HEADER
../utilities/protos HYPRE_cgnr.c          >> $INTERNAL_HEADER
../utilities/protos HYPRE_gmres.c         >> $INTERNAL_HEADER
../utilities/protos HYPRE_flexgmres.c         >> $INTERNAL_HEADER
../utilities/protos HYPRE_lgmres.c         >> $INTERNAL_HEADER
../utilities/protos HYPRE_pcg.c           >> $INTERNAL_HEADER
../utilities/protos pcg.c                 >> $INTERNAL_HEADER

#===========================================================================
# Include guards
#===========================================================================

cat >> $INTERNAL_HEADER <<@

#ifdef __cplusplus
}
#endif

#endif

@

