#!/bin/sh
# Copyright (c) 1998 Lawrence Livermore National Security, LLC and other
# HYPRE Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

../config/gen_code.sh HYPRE_krylov.h _hypre_krylov.h mup
../config/gen_code.sh HYPRE_lobpcg.h lobpcg.h        mup_lobpcg

mup_headers
mup_lobpcg_headers
