#!/bin/sh
#BHEADER***********************************************************************
# (c) 1996   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision$
#EHEADER***********************************************************************

#=============================================================================
# This Script attempts to determine the architecture to use.
#=============================================================================

AMG_OS=""
AMG_ARCH=""

#=============================================================================
# Determine the OS
#=============================================================================

if [ -f "/bin/uname" ] 
then
   AMG_OS="`/bin/uname -s`"
   AMG_OS_Release="`/bin/uname -r`"
fi

#=============================================================================
# Based on what we found from system queries set AMG_ARCH
#=============================================================================

if [ -z "$AMG_ARCH" ]
then
   case "$AMG_OS" in
      SunOS)
         case "$AMG_OS_Release" in	
            4.1.3) AMG_ARCH="sunos";;
            5.4)   AMG_ARCH="solaris";;
            5.5)   AMG_ARCH="solaris";;
         esac;;
      IRIX64)
         AMG_ARCH="irix";;
      OSF1)
         AMG_ARCH="dec";;
      CYGWIN32/95)
         AMG_ARCH="cygwin32";;
      CYGWIN32/NT)
         AMG_ARCH="cygwin32";;
   esac
fi

