#!/bin/sh
#BHEADER***********************************************************************
# (c) 1996   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision$
#EHEADER***********************************************************************

#===========================================================================
# This script builds the AMG library
#===========================================================================

AMG_SRC=".."

. $AMG_SRC/config/build_generic

#=============================================================================
# Set various flags
#=============================================================================

CFLAGS="$AMG_CC_FLAGS"
FFLAGS="$AMG_F77_FLAGS"

if [ "$AMG_OPTIMIZE_FLAG" ]
then
   CFLAGS="$CFLAGS $AMG_CC_OPT"
   FFLAGS="$FFLAGS $AMG_F77_OPT"
fi

if [ "$AMG_DEBUG_FLAG" ]
then
   CFLAGS="$CFLAGS $AMG_CC_DEBUG"
   FFLAGS="$FFLAGS $AMG_F77_DEBUG"
fi

#=============================================================================
# Export variables needed by make
#=============================================================================

export AMG_LIBRARY AMG_FILES AMG_HEADERS
export AMG_CC CFLAGS AMG_F77 FFLAGS
export AMG_AR AMG_RANLIB
export AMG_INSTALL AMG_LIB_DIR AMG_INCLUDE_DIR

#=============================================================================
# Build
#=============================================================================

if [ "$AMG_ALL_FLAG" ]
then
   echo ""
   echo "Building library $AMG_LIBRARY"
   echo "       Arch:                   $AMG_ARCH"
   echo "       CC Options:             $CFLAGS"
   echo "       F77 Options:            $FFLAGS"

   $AMG_MAKE

   echo "done"
   echo ""
fi

#=============================================================================
# Install
#=============================================================================

if [ "$AMG_INSTALL_FLAG" ]
then
   for i in $AMG_LIB_DIR $AMG_INCLUDE_DIR
   do
      if [ ! -d $i ]
      then
         $AMG_MKDIR $i
      fi
   done

   $AMG_MAKE install
fi

#=============================================================================
# Clean
#=============================================================================

if [ "$AMG_CLEAN_FLAG" ]
then
   $AMG_MAKE clean
fi

if [ "$AMG_VERYCLEAN_FLAG" ]
then
   $AMG_MAKE veryclean
   rm -f $AMG_LIBRARY.$AMG_ARCH.a
fi

