#!/bin/sh
#BHEADER***********************************************************************
# (c) 1996   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision$
#EHEADER***********************************************************************

#===========================================================================
# This script builds the AMG code
#===========================================================================

. $AMG_SRC/config/build_generic

#=============================================================================
# Set various flags
#=============================================================================

AMG_LIBRARY=amg

CFLAGS="$AMG_CC_FLAGS -I$AMG_SRC/config"
FFLAGS="$AMG_F77_FLAGS"
LFLAGS="$AMG_LINK_FLAGS"

if [ "$AMG_OPTIMIZE_FLAG" ]
then
   CFLAGS="$CFLAGS $AMG_CC_OPT"
   FFLAGS="$FFLAGS $AMG_F77_OPT"
fi

if [ "$AMG_DEBUG_FLAG" ]
then
   CFLAGS="$CFLAGS $AMG_CC_DEBUG"
   FFLAGS="$FFLAGS $AMG_F77_DEBUG"
fi

export AMG_LIBRARY CFLAGS FFLAGS LFLAGS

#=============================================================================
# Build
#=============================================================================

if [ "$AMG_ALL_FLAG" ]
then
   echo "Building"
   echo "       Library:                $AMG_LIBRARY"
   echo "       Arch:                   $AMG_ARCH"
   echo "       CC Options:             $CFLAGS"
   echo "       F77 Options:            $FFLAGS"

   # define AMG_FILES
   AMG_FILES=`cat rcs_files | \
      awk '
         BEGIN {STR = " "}
         {
           for (i = 1; i <= NF; i++) {
             if (($i ~ /[^\ ]*\.c/) || \
                 ($i ~ /[^\ ]*\.f/)    )
               STR = STR $i " "
           }
         }
         END {print STR}
      '`

   export AMG_FILES

   $AMG_MAKE $AMG_LIBRARY.$AMG_ARCH.a

   echo "done"
fi

#=============================================================================
# Install
#=============================================================================

if [ "$AMG_INSTALL_FLAG" ]
then
   AMG_LIB=$AMG_DIR/lib

   if [ ! -d $AMG_LIB ]
   then
     $AMG_MKDIR $AMG_LIB
   fi

   AMG_INCLUDE=$AMG_DIR/include

   if [ ! -d $AMG_INCLUDE ]
   then
     $AMG_MKDIR $AMG_INCLUDE
   fi

   $AMG_INSTALL $AMG_LIBRARY.$AMG_ARCH.a $AMG_LIB/lib$AMG_LIBRARY.a
   $AMG_INSTALL amg.h vector.h matrix.h $AMG_INCLUDE
fi

#=============================================================================
# Clean
#=============================================================================

if [ "$AMG_CLEAN_FLAG" ]
then
   rm -f *.$AMG_ARCH.o
fi

if [ "$AMG_VERYCLEAN_FLAG" ]
then
   rm -f $AMG_LIBRARY.$AMG_ARCH.a
fi

