#BHEADER***********************************************************************
# (c) 2000   The Regents of the University of California
#
# See the file COPYRIGHT for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision: 1.1 $
#EHEADER***********************************************************************

HYPRE_EIGENSOLVE_BUILDDIR = lib

all: 
	for dir in ${HYPRE_EIGENSOLVE_BUILDDIR};  do  (cd $$dir && $(MAKE)) || exit 1; done

install:
	for dir in ${HYPRE_EIGENSOLVE_BUILDDIR};  do  (cd $$dir && $(MAKE)) || exit 1; done

clean:
	for dir in ${HYPRE_EIGENSOLVE_BUILDDIR};  do  (cd $$dir && $(MAKE)) || exit 1; done

distclean:
	for dir in ${HYPRE_EIGENSOLVE_BUILDDIR};  do  (cd $$dir && $(MAKE)) || exit 1; done
