#!/bin/sh

##################################################################
# To use:
#
#   1) Make a backup of your source files
#   
#   	 mkdir BACKUP
#   	 cp * BACKUP
#   
#   2) If your old prefixes are not `zzz_' and `ZZZ_', then edit the
#      `change_prefix.sed' file so that it has the correct old prefixes.
#   
#   3) Type `change_prefix <files>'
#
#   4) Try recompiling and running before committing to repository
#
##################################################################

for i in $*
do
  cp $i $i.tmp
  sed -f change_prefix.sed $i.tmp > $i
  rm -f $i.tmp
done

