#!/bin/sh
#BHEADER**********************************************************************
# Copyright (c) 2008,  Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory.
# This file is part of HYPRE.  See file COPYRIGHT for details.
#
# HYPRE is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License (as published by the Free
# Software Foundation) version 2.1 dated February 1999.
#
# $Revision$
#EHEADER**********************************************************************







#-----------------------------------------------------------------------------
#
# Usage:  amgcpio <prefix1> <prefix2>
#
# Result: cp <prefix1>.in.problem  <prefix2>.in.problem
#         cp <prefix1>.in.solver   <prefix2>.in.solver
#         cp <prefix1>.out*        <prefix2>.out*
#
#=============================================================================

if [ "$2" != "" ]; then

for i in $1.in.problem $1.in.solver $1.out*
do
  EXT=`echo $i $1 | awk '{print substr($1,length($2)+1)}'`
  cp $i $2${EXT}
done


else

  echo 'usage:  amgcpio <prefix1> <prefix2>'
  echo 'result: cp <prefix1>.in.problem  <prefix2>.in.problem'
  echo '        cp <prefix1>.in.solver   <prefix2>.in.solver'
  echo '        cp <prefix1>.out*        <prefix2>.out*'

fi

