#!/bin/sh
#BHEADER**********************************************************************
# Copyright (c) 2006   The Regents of the University of California.
# Produced at the Lawrence Livermore National Laboratory.
# Written by the HYPRE team <hypre-users@llnl.gov>, UCRL-CODE-222953.
# All rights reserved.
#
# This file is part of HYPRE (see http://www.llnl.gov/CASC/hypre/).
# Please see the COPYRIGHT_and_LICENSE file for the copyright notice, 
# disclaimer and the GNU Lesser General Public License.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License (as published by the Free
# Software Foundation) version 2.1 dated February 1999.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the IMPLIED WARRANTY OF MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the terms and conditions of the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
# $Revision$
#EHEADER**********************************************************************

#-----------------------------------------------------------------------------
#
# Usage:  amgcpio <prefix1> <prefix2>
#
# Result: cp <prefix1>.in.problem  <prefix2>.in.problem
#         cp <prefix1>.in.solver   <prefix2>.in.solver
#         cp <prefix1>.out*        <prefix2>.out*
#
#=============================================================================

if [ "$2" != "" ]; then

for i in $1.in.problem $1.in.solver $1.out*
do
  EXT=`echo $i $1 | awk '{print substr($1,length($2)+1)}'`
  cp $i $2${EXT}
done


else

  echo 'usage:  amgcpio <prefix1> <prefix2>'
  echo 'result: cp <prefix1>.in.problem  <prefix2>.in.problem'
  echo '        cp <prefix1>.in.solver   <prefix2>.in.solver'
  echo '        cp <prefix1>.out*        <prefix2>.out*'

fi

