#!/bin/sh
#BHEADER**********************************************************************
# Copyright (c) 2007, Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory.
# Written by the HYPRE team. UCRL-CODE-222953.
# All rights reserved.
#
# This file is part of HYPRE (see http://www.llnl.gov/CASC/hypre/).
# Please see the COPYRIGHT_and_LICENSE file for the copyright notice, 
# disclaimer, contact information and the GNU Lesser General Public License.
#
# HYPRE is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License (as published by the Free Software 
# Foundation) version 2.1 dated February 1999.
#
# HYPRE is distributed in the hope that it will be useful, but WITHOUT ANY 
# WARRANTY; without even the IMPLIED WARRANTY OF MERCHANTABILITY or FITNESS 
# FOR A PARTICULAR PURPOSE.  See the terms and conditions of the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
# $Revision$
#EHEADER**********************************************************************





#-----------------------------------------------------------------------------
#
# Usage:  amgmvio <prefix1> <prefix2>
#
# Result: mv <prefix1>.in.problem  <prefix2>.in.problem
#         mv <prefix1>.in.solver   <prefix2>.in.solver
#         mv <prefix1>.out*        <prefix2>.out*
#
#=============================================================================

if [ "$2" != "" ]; then

for i in $1.in.problem $1.in.solver $1.out*
do
  EXT=`echo $i $1 | awk '{print substr($1,length($2)+1)}'`
  mv $i $2${EXT}
done


else

  echo 'usage:  amgmvio <prefix1> <prefix2>'
  echo 'result: mv <prefix1>.in.problem  <prefix2>.in.problem'
  echo '        mv <prefix1>.in.solver   <prefix2>.in.solver'
  echo '        mv <prefix1>.out*        <prefix2>.out*'

fi

