#!/bin/sh
#BHEADER***********************************************************************
# (c) 1996   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision$
#EHEADER***********************************************************************

#===========================================================================
# This script builds the AMG tools
#===========================================================================

. $AMG_SRC/config/build_generic

#=============================================================================
# Set various flags
#=============================================================================

CFLAGS=""
FFLAGS=""
LFLAGS=""

if [ "$AMG_OPTIMIZE_FLAG" ]
then
   CFLAGS="$CFLAGS -O"
   FFLAGS="$FFLAGS -O"
fi

if [ "$AMG_DEBUG_FLAG" ]
then
   CFLAGS="$CFLAGS -g"
   FFLAGS="$FFLAGS -g"
fi

export CFLAGS FFLAGS LFLAGS

#=============================================================================
# Build
#=============================================================================

if [ "$AMG_ALL_FLAG" ]
then
   # if on a new arch, first clean everything
   if [ "$AMG_ARCH" != "$AMG_OLD_ARCH" ]
   then
      ./build veryclean
   fi

   $AMG_MAKE
fi

#=============================================================================
# Install
#=============================================================================

if [ "$AMG_INSTALL_FLAG" ]
then
   AMG_BIN=$AMG_DIR/bin

   if [ ! -d $AMG_BIN ]
   then
     $AMG_MKDIR $AMG_BIN
   fi

   UTILITIES="amgstrip amgmvio convert_icf3d readysmp.m readvec.m"

   for i in $UTILITIES
   do
      $AMG_INSTALL $AMG_SRC/tools/$i $AMG_BIN/.
   done
fi

#=============================================================================
# Clean
#=============================================================================

if [ "$AMG_CLEAN_FLAG" ]
then
   rm -f *.o
fi

if [ "$AMG_VERYCLEAN_FLAG" ]
then
   UTILITIES="convert_icf3d"

   for i in $UTILITIES
   do
      rm -f $i
   done
fi

