#!/bin/sh
#BHEADER***********************************************************************
# (c) 1996   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision$
#EHEADER***********************************************************************

#===========================================================================
# This script builds the AMG_FDRIVER code
#===========================================================================

. $AMG_SRC/config/build_generic

#=============================================================================
# Set various flags
#=============================================================================

AMG_FDRIVER="amg_fdrive"

LIBRARY_DIRS="amg"
 
CFLAGS="$AMG_CC_FLAGS -I$AMG_SRC/config -I$AMG_DIR/include"
FFLAGS="$AMG_F77_FLAGS"
LFLAGS="$AMG_LINK_FLAGS"

if [ "$AMG_OPTIMIZE_FLAG" ]
then
   CFLAGS="$CFLAGS $AMG_CC_OPT"
   FFLAGS="$FFLAGS $AMG_F77_OPT"
fi

if [ "$AMG_DEBUG_FLAG" ]
then
   CFLAGS="$CFLAGS $AMG_CC_DEBUG"
   FFLAGS="$FFLAGS $AMG_F77_DEBUG"
fi

export AMG_FDRIVER CFLAGS FFLAGS LFLAGS

#=============================================================================
# Build
#=============================================================================

if [ "$AMG_ALL_FLAG" ]
then
   for i in $LIBRARY_DIRS
   do
      (cd $AMG_SRC/$i; ./build $AMG_BUILD_ARGS install)
   done

   echo "Building"
   echo "       Program:                $AMG_FDRIVER"
   echo "       Arch:                   $AMG_ARCH"
   echo "       CC Options:             $CFLAGS"
   echo "       F77 Options:            $FFLAGS"

   # define AMG_FILES

    AMG_FILES='amg_fdrive.f'

#   AMG_FILES=`cat rcs_files | \
#      awk '
#         BEGIN {STR = " "}
#         {
#           for (i = 1; i <= NF; i++) {
#             if (($i ~ /[^\ ]*\.c/) || \
#                 ($i ~ /[^\ ]*\.f/)    )
#               STR = STR $i " "
#           }
#         }
#         END {print STR}
#      '`

   export AMG_FILES

   $AMG_MAKE $AMG_FDRIVER.$AMG_ARCH

   echo "done"
fi

#=============================================================================
# Install
#=============================================================================

if [ "$AMG_INSTALL_FLAG" ]
then
   $AMG_INSTALL $AMG_SRC/amg_fdrive/$AMG_FDRIVER.$AMG_ARCH \
                $AMG_BIN_DIR/$AMG_FDRIVER
fi

#=============================================================================
# Clean
#=============================================================================

if [ "$AMG_CLEAN_FLAG" ]
then
   for i in $LIBRARY_DIRS
   do
      (cd $AMG_SRC/$i; ./build $AMG_BUILD_ARGS)
   done

   rm -f *.$AMG_ARCH.o
fi

if [ "$AMG_VERYCLEAN_FLAG" ]
then
   for i in $LIBRARY_DIRS
   do
      (cd $AMG_SRC/$i; ./build $AMG_BUILD_ARGS)
   done

   rm -f $AMG_FDRIVER.$AMG_ARCH
fi

