#!/bin/ksh
# create symbolic links to the hypre tar ball distribution
# executed in /usr/casc/hypre and /usr/gapps/hypre
DIR="\
 alphaev67-dec-osf5.1\
 alphaev67-unknown-linux-gnu\
 alphaev68-dec-osf5.1\
 i686-pc-linux-gnu\
 i686-pc-linux-ilx\
 i686-pc-linux-gnu-pengra\
 mips-sgi-irix6.5\
 powerpc-ibm-aix5.1.0.0\
 powerpcll-ibm-aix5.1.0.0\
 sparc-sun-solaris2.7\
 sparc-sun-solaris2.8"
if [ $# -ne 1 ]
then printf "usage: $0 HypreArchiveFile\n"
  exit 1
else TAR_FILE=$1
fi
if [ -f $TAR_FILE ]
then for i in $DIR
  do if [ -d $i ]
    then ( cd $i; ln -s ../$TAR_FILE $TAR_FILE)
      ls -l $i/$TAR_FILE
    fi
  done
else print "can not find $TAR_FILE"
  exit 1
fi
