#!/bin/ksh
#BHEADER**********************************************************************
# Copyright (c) 2006   The Regents of the University of California.
# Produced at the Lawrence Livermore National Laboratory.
# Written by the HYPRE team <hypre-users@llnl.gov>, UCRL-CODE-222953.
# All rights reserved.
#
# This file is part of HYPRE (see http://www.llnl.gov/CASC/hypre/).
# Please see the COPYRIGHT_and_LICENSE file for the copyright notice, 
# disclaimer and the GNU Lesser General Public License.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License (as published by the Free
# Software Foundation) version 2.1 dated February 1999.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the IMPLIED WARRANTY OF MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the terms and conditions of the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
# $Revision$
#EHEADER**********************************************************************


#
# MaKe hypre DISTribution
# This script is used to create the hypre distribution tar files.
# Run on the CASC cluster from the users local directory space.
#

help ()
{
  printf "$0: [-help] | [-display] | VersionId\n"
  printf " where:\n"
  printf " -help displays this message.\n"
  printf " -display will report the cvs rtag history.\n"
  printf " VersionId, is the desired version identification\n"
  printf "  (e.g., V1-2-0 which creates tar file hypre-1.2.0.tar.gz).\n"
  printf "  \n"
  printf "  VersionID is used in the tar file name and as the root\n"
  printf "  directory name for the distribution.\n"
  printf "  \n"
  printf "  By convention, the syntax for VersionId is: \"M.mm.rr\";\n"
  printf "  where \"M\" is the major release number, \"mm\" is the minor\n"
  printf "  number, and \"rr\" an update number.\n"
  printf "  \n"
  printf "  The number syntax within the repository is VM-mm-rr so that is\n"
  printf "  the format input to this script.\n"
  printf "  \n"
  printf "  Alpha releases are denoted as \"VM-nn-rr-a\" and \"VM-nn-rr-b\" for\n"
  printf "  beta releases.\n"
  printf "  \n"
  printf "  If VersionId can be mapped to a valid rtag branch from the source\n"
  printf "  repository; it is assumed that the rtag id will follow the naming\n"
  printf "  convention, \"VM-nn-rr\".  If the VersionId can not be mapped to a\n"
  printf "  current rtag id an error message is generated.\n"
  printf "  \n"
}

usage ()
{
  printf "usage: $0 VersionId\n"
}

display ()
{
  printf "valid cvs rtags:\n"
  cvs history -T -a | grep linear_solvers
}

#=============================================================================
# Parse arguments
#=============================================================================

case $1 in
    -h|-help) 
        help
        exit;;
    -d|-disp|-display) 
        display
        exit;;
esac

if [ $# -gt 0 ]
then
  VersionId=$1
  RtagVersionId=${VersionId}
else
  usage
  exit
fi

#===========================================================================
# Update the source
#===========================================================================

# create dist directory
HYPRE_DIR="hypre-${VersionId}"
HYPRE_DIST_INSTALL_DIR=`pwd`"/$HYPRE_DIR"
export HYPRE_DIST_INSTALL_DIR
mkdir -p $HYPRE_DIST_INSTALL_DIR
mkdir $HYPRE_DIST_INSTALL_DIR/src

# check the source code out of the repository
(
  cd $HYPRE_DIST_INSTALL_DIR/src
  if [ ! -d "$CVSROOT" ]
  then
    echo "Error: no CVS repository, CVSROOT = $CVSROOT"
    exit
  fi
  cvs export -r ${RtagVersionId} linear_solvers
  if [  $? -ne 0 ]
  then
    echo "Error: Rtag Version=${RtagVersionId} not found in CVS repository"
    display
    exit
  fi
)

## replace dashes in version number with dots and redefine directory names
Version=`echo ${RtagVersionId}|cut -c2- |sed 's/-/\./g'`
if [  $? -ne 0 ]
then
  echo "Error: CVS repository defective"
  exit
fi
mv $HYPRE_DIR "hypre-${Version}"
HYPRE_DIR="hypre-${Version}"
HYPRE_DIST_INSTALL_DIR=`pwd`"/$HYPRE_DIR"
    
# build documentation for examples sub-directory
(
  cd $HYPRE_DIST_INSTALL_DIR/src/linear_solvers/examples/docs
  make
)
    
# build documentation and install in the distribution directory
(
  cd $HYPRE_DIST_INSTALL_DIR/src/linear_solvers
  ./configure --prefix=$HYPRE_DIST_INSTALL_DIR
  (cd docs; make install)
)
    
# store version info
(
  cd $HYPRE_DIST_INSTALL_DIR
  cp src/linear_solvers/COPYRIGHT_and_LICENSE .
  cp src/linear_solvers/CHANGELOG .
  cp src/linear_solvers/INSTALL .
  cp src/linear_solvers/README .
)

# pop 'linear_solvers' directory to 'src'
mv $HYPRE_DIR/src/linear_solvers/* $HYPRE_DIR/src
rmdir $HYPRE_DIR/src/linear_solvers

# create the hypre-${VersionId}.tar file
echo "creating $HYPRE_DIR.tar file ..."
tar cf $HYPRE_DIR.tar \
    $HYPRE_DIR/CHANGELOG \
    $HYPRE_DIR/COPYRIGHT_and_LICENSE \
    $HYPRE_DIR/INSTALL \
    $HYPRE_DIR/README \
    $HYPRE_DIR/docs \
    $HYPRE_DIR/src/FEI_mv \
    $HYPRE_DIR/src/HYPRE.h \
    $HYPRE_DIR/src/IJ_mv \
    $HYPRE_DIR/src/Makefile \
    $HYPRE_DIR/src/aclocal.m4 \
    $HYPRE_DIR/src/babel \
    $HYPRE_DIR/src/babel-runtime \
    $HYPRE_DIR/src/blas \
    $HYPRE_DIR/src/config \
    $HYPRE_DIR/src/configure \
    $HYPRE_DIR/src/distributed_ls \
    $HYPRE_DIR/src/distributed_matrix \
    $HYPRE_DIR/src/examples/ex* \
    $HYPRE_DIR/src/examples/Make* \
    $HYPRE_DIR/src/examples/README.html \
    $HYPRE_DIR/src/examples/README_files \
    $HYPRE_DIR/src/krylov \
    $HYPRE_DIR/src/lapack \
    $HYPRE_DIR/src/lib \
    $HYPRE_DIR/src/matrix_matrix \
    $HYPRE_DIR/src/multivector \
    $HYPRE_DIR/src/nopoe \
    $HYPRE_DIR/src/parcsr_block_mv \
    $HYPRE_DIR/src/parcsr_ls \
    $HYPRE_DIR/src/parcsr_mv \
    $HYPRE_DIR/src/seq_mv \
    $HYPRE_DIR/src/sstruct_ls \
    $HYPRE_DIR/src/sstruct_mv \
    $HYPRE_DIR/src/struct_ls \
    $HYPRE_DIR/src/struct_mv \
    $HYPRE_DIR/src/tarch \
    $HYPRE_DIR/src/test \
    $HYPRE_DIR/src/utilities

gzip $HYPRE_DIR.tar
