#!/bin/sh
# Copyright (c) 1998 Lawrence Livermore National Security, LLC and other
# HYPRE Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

## Should be run from src directory
# Loops over directories with multiprecision files and generates code.

DIRS="\
 IJ_mv\
 blas\
 distributed_ls/Euclid\
 distributed_ls/ParaSails\
 krylov\
 lapack\
 parcsr_ls\
 parcsr_mv\
 seq_block_mv\
 seq_mv\
 sstruct_ls\
 sstruct_mv\
 struct_ls\
 struct_mv\
 utilities\
"
# distributed_ls/pilut     - no external header, no internal header
# distributed_matrix       - no external header, no internal header
# matrix_matrix            - no external header, no internal header
# multivector              - no external header, no internal header
# parcsr_block_mv          - no external header

for i in $DIRS
do
    echo "Writing multiprecision code for $i ..."
    (cd $i; mup_code)
done

