#!/bin/sh
# Copyright (c) 1998 Lawrence Livermore National Security, LLC and other
# HYPRE Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

DIRS="\
 IJ_mv\
 krylov\
 parcsr_ls\
 parcsr_mv\
 sstruct_ls\
 sstruct_mv\
 struct_ls\
 struct_mv\
"
# blas                     - no external header
# distributed_ls/Euclid    - no external header
# distributed_ls/ParaSails - no external header, no internal header
# distributed_ls/pilut     - no external header, no internal header
# distributed_matrix       - no external header, no internal header
# lapack                   - no external header
# matrix_matrix            - no external header, no internal header
# multivector              - no external header, no internal header
# parcsr_block_mv          - no external header
# seq_block_mv             - no external header
# seq_mv                   - rename seq_mv.h to _hypre_seq_mv.h
# utilities

for i in $DIRS
do
    echo "Writing multiprecision code for $i ..."
    (cd $i; mup_code)
done

