#!/bin/sh
#BHEADER**********************************************************************
# Copyright (c) 2008,  Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory.
# This file is part of HYPRE.  See file COPYRIGHT for details.
#
# HYPRE is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License (as published by the Free
# Software Foundation) version 2.1 dated February 1999.
#
# $Revision$
#EHEADER**********************************************************************









amgstrip $1.in.solver $1.in.solver.strp
amgstrip $1.in.problem $1.in.problem.strp

amgdriver $1

if  [ "$2" != "debug" ] 
then
    rm -f $1.in.solver.strp $1.in.problem.strp
fi
