#! /bin/sh
#BHEADER***********************************************************************
# (c) 1996   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision$
#EHEADER***********************************************************************


amgstrip $1.in.solver $1.in.solver.strp
amgstrip $1.in.problem $1.in.problem.strp

amgdriver $1

if  [ "$2" != "debug" ] 
then
    rm -f $1.in.solver.strp $1.in.problem.strp
fi
