#!/bin/sh
#BHEADER**********************************************************************
# Copyright (c) 2006   The Regents of the University of California.
# Produced at the Lawrence Livermore National Laboratory.
# Written by the HYPRE team <hypre-users@llnl.gov>, UCRL-CODE-222953.
# All rights reserved.
#
# This file is part of HYPRE (see http://www.llnl.gov/CASC/hypre/).
# Please see the COPYRIGHT_and_LICENSE file for the copyright notice, 
# disclaimer and the GNU Lesser General Public License.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License (as published by the Free
# Software Foundation) version 2.1 dated February 1999.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the IMPLIED WARRANTY OF MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the terms and conditions of the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
# $Revision$
#EHEADER**********************************************************************


#===========================================================================
# This script builds the AMG code
#===========================================================================

AMG_SRC=".."

. $AMG_SRC/config/build_generic

#=============================================================================
# Make sure needed libraries are installed
#=============================================================================

LIBRARY_DIRS="amg cvode"
 
if [ "$AMG_ALL_FLAG" ]
then
   AMG_BUILD_ARGS="$AMG_BUILD_ARGS install"
fi

for i in $LIBRARY_DIRS
do
   (cd $AMG_SRC/$i; ./build $AMG_BUILD_ARGS)
done

#=============================================================================
# Set various flags
#=============================================================================

CFLAGS="$AMG_CC_FLAGS"
FFLAGS="$AMG_F77_FLAGS"
LFLAGS="$AMG_LINK_FLAGS"

if [ "$AMG_OPTIMIZE_FLAG" ]
then
   CFLAGS="$CFLAGS $AMG_CC_OPT"
   FFLAGS="$FFLAGS $AMG_F77_OPT"
fi

if [ "$AMG_DEBUG_FLAG" ]
then
   CFLAGS="$CFLAGS $AMG_CC_DEBUG"
   FFLAGS="$FFLAGS $AMG_F77_DEBUG"
fi

#=============================================================================
# Export variables needed by make
#=============================================================================

export AMG_DRIVER AMG_FILES AMG_HEADERS
export AMG_CC CFLAGS AMG_F77 FFLAGS
export AMG_LINK LFLAGS
export AMG_INSTALL AMG_BIN_DIR

#=============================================================================
# Build
#=============================================================================

if [ "$AMG_ALL_FLAG" ]
then
   echo ""
   echo "Building program $AMG_DRIVER"
   echo "       Arch:                   $AMG_ARCH"
   echo "       CC Options:             $CFLAGS"
   echo "       F77 Options:            $FFLAGS"

   $AMG_MAKE

   echo "done"
   echo ""
fi

#=============================================================================
# Install
#=============================================================================

if [ "$AMG_INSTALL_FLAG" ]
then
   if [ ! -d "$AMG_BIN_DIR" ]
   then
      $AMG_MKDIR $i
   fi

   $AMG_MAKE install
fi

#=============================================================================
# Clean
#=============================================================================

if [ "$AMG_CLEAN_FLAG" ]
then
   $AMG_MAKE clean
fi

if [ "$AMG_VERYCLEAN_FLAG" ]
then
   $AMG_MAKE veryclean
fi

