#!/bin/sh

echo " "
echo " setMake"
echo " "

if [ $1 ]; then \
   echo "checking for file setup/make.options.$1..."; \
   echo " "; \
else \
   echo "ERROR, setMake requires an argument"; \
   echo "Usage: setMake <system>"; \
   echo "  where <system> is the extension of a file in the setup directory."; \
   echo " "; \
   exit; \
fi

if [ -f setup/make.options.$1 ]; then \
   echo "... setting paths and copying setup/make.options.$1 to make.options"; \
   echo " "; \
else \
   echo "ERROR, setup/make.options.$1 not found."; \
   echo " "; \
   exit; \
fi

FEI_ROOT=`pwd`

echo "FEI_ROOT=$FEI_ROOT" >> make.tmp
echo "ISIS_ROOT=$FEI_ROOT/../isis" >> make.tmp
cat make.tmp setup/make.options.$1 > make.options
rm make.tmp

echo "IMPORTANT NOTE: IF ISIS++ is not located in"
echo "$FEI_ROOT/../isis, then you need to edit the"
echo "'ISIS_ROOT' variable in make.options."
echo " "
echo "Depending on your system, you may also need to edit"
echo "the MPI paths and/or paths to other libraries."
echo " "
echo "You may now build fei-isis with make." 
echo " "

