#!/bin/csh

cd ../../utilities
make -f MakeIRIX clean
make -f MakeIRIX
cd ../seq_matrix_vector
make -f MakeIRIX clean
make -f MakeIRIX 
cd ../PETSc_linear_solvers/amg
make -f MakeIRIX clean
make -f MakeIRIX 

